import type { LangCode } from './types'
import type { InternalPageCopy, InternalPageFaqItem } from './extra'

type Phase3BPageKey = 'decisionTracking' | 'governmentGovernance' | 'listedCompaniesGovernance' | 'bankingGovernance'
type LString = Record<LangCode, string>
type LList = Record<LangCode, string[]>
type LFaq = Record<LangCode, InternalPageFaqItem[]>

type Labels = {
  solution: string
  industry: string
  direct: string
  problems: string
  solutionTitle: string
  capabilities: string
  workflow: string
  governance: string
  proof: string
  outcomes: string
  executive: string
}

const labels: Record<LangCode, Labels> = {
  ar: { solution: 'الحلول', industry: 'القطاعات المنظمة', direct: 'لمحة سريعة', problems: 'تحديات تشغيلية قائمة', solutionTitle: 'كيف يعالجها ديوان سويت', capabilities: 'قدرات أساسية', workflow: 'كيف يعمل المسار', governance: 'الأثر الحوكمي والرقابي', proof: 'شواهد تشغيلية', outcomes: 'مخرجات تنفيذية قابلة للقياس', executive: 'ملخص تنفيذي' },
  en: { solution: 'Solutions', industry: 'Regulated Sectors', direct: 'Quick overview', problems: 'Current operational pain', solutionTitle: 'How Diwan Suite addresses it', capabilities: 'Key capabilities', workflow: 'How the workflow operates', governance: 'Governance, compliance, and audit impact', proof: 'Operational proof points', outcomes: 'Executive outcomes', executive: 'Executive Summary' },

  hi: { solution: 'समाधान', industry: 'विनियमित行业', direct: 'त्वरित परिचय', problems: 'वर्तमान परिचालन चुनौतियाँ', solutionTitle: 'Diwan Suite इसे कैसे संभालता है', capabilities: 'मुख्य क्षमताएँ', workflow: 'वर्कफ़्लो कैसे चलता है', governance: 'गवर्नेंस, अनुपालन और ऑडिट प्रभाव', proof: 'ऑपरेशनल प्रमाण', outcomes: 'कार्यकारी परिणाम', executive: 'कार्यकारी सार' },
  ur: { solution: 'حلول', industry: 'منظم شعبے', direct: 'مختصر جائزہ', problems: 'موجودہ آپریشنل چیلنجز', solutionTitle: 'Diwan Suite مسئلہ کیسے حل کرتا ہے', capabilities: 'اہم صلاحیتیں', workflow: 'ورک فلو کیسے چلتا ہے', governance: 'گورننس، تعمیل اور آڈٹ اثرات', proof: 'عملی شواہد', outcomes: 'انتظامی نتائج', executive: 'ایگزیکٹو خلاصہ' },

}

type Def = {
  key: Phase3BPageKey
  eyebrow: 'solution' | 'industry'
  titles: LString
  summary: LString
  seoTitle: LString
  seoDescription: LString
  definition: LString
  whoFor: LList
  whatItSolves: LList
  howItWorks: LList
  capabilities: LList
  governance: LList
  proof: LList
  outcomes: LList
  faq: LFaq
  relatedPages: string[]
}

function copy(lang: LangCode, page: Def): InternalPageCopy {
  const t = labels[lang]
  return {
    eyebrow: page.eyebrow === 'industry' ? t.industry : t.solution,
    title: page.titles[lang],
    summary: page.summary[lang],
    seoTitle: page.seoTitle[lang],
    seoDescription: page.seoDescription[lang],
    executiveSummary: t.executive,
    definition: page.definition[lang],
    whoFor: page.whoFor[lang],
    whatItSolves: page.whatItSolves[lang],
    howItWorks: page.howItWorks[lang],
    faq: page.faq[lang],
    relatedPages: page.relatedPages,
    sections: [
      { id: 'problems', title: t.problems, body: [page.summary[lang]], bullets: page.whatItSolves[lang] },
      { id: 'solution-overview', title: t.solutionTitle, body: [page.definition[lang]], bullets: page.capabilities[lang] },
      { id: 'key-capabilities', title: t.capabilities, body: [], bullets: page.capabilities[lang] },
      { id: 'workflow', title: t.workflow, body: [], bullets: page.howItWorks[lang] },
      { id: 'governance-impact', title: t.governance, body: [], bullets: page.governance[lang] },
      { id: 'proof', title: t.proof, body: [page.summary[lang]], bullets: page.proof[lang] },
      { id: 'executive-outcomes', title: t.outcomes, body: [], bullets: page.outcomes[lang] },
    ],
  }
}

const pages: Def[] = [
  {
    key: 'decisionTracking',
    eyebrow: 'solution',
    titles: { ar: 'إدارة ومتابعة القرارات', en: 'Decision Management & Tracking',    hi: 'निर्णय प्रबंधन और ट्रैकिंग', ur: 'فیصلہ جات کا نظم اور ٹریکنگ'},
    summary: { ar: 'تحويل كل قرار معتمد إلى مهمة قابلة للتنفيذ مع مالك واضح وأولوية وتاريخ استحقاق وتنبيهات وتصعيد تنفيذي.', en: 'Turn every approved decision into an executable task with a clear owner, priority, due date, alerts, and executive escalation.',    hi: 'हर स्वीकृत निर्णय को स्पष्ट मालिक, प्राथमिकता, नियत तिथि, अलर्ट और एस्केलेशन वाले कार्य में बदलें।', ur: 'ہر منظور شدہ فیصلے کو واضح مالک، ترجیح، تاریخِ تکمیل، تنبیہات اور تصعید والے کام میں بدلیں۔'},
    seoTitle: { ar: 'إدارة ومتابعة القرارات | ديوان سويت', en: 'Decision Management & Tracking | Diwan Suite',    hi: 'निर्णय प्रबंधन और ट्रैकिंग | Diwan Suite', ur: 'فیصلہ جات کا نظم اور ٹریکنگ | Diwan Suite'},
    seoDescription: { ar: 'إدارة ومتابعة القرارات من ديوان سويت لتحويل قرارات المجلس واللجان إلى مهام قابلة للتنفيذ مع تنبيهات وتصعيد وتقارير تنفيذية واضحة.', en: 'Diwan Suite decision management and tracking for turning board and committee decisions into executable tasks with alerts, escalation, and executive reporting.',    hi: 'Diwan Suite निर्णय प्रबंधन और ट्रैकिंग, बोर्ड और समिति निर्णयों को अलर्ट, एस्केलेशन और रिपोर्टिंग सहित कार्यों में बदलता है।', ur: 'Diwan Suite میں فیصلہ جات کا نظم اور ٹریکنگ بورڈ و کمیٹی فیصلوں کو تنبیہات اور تصعید کے ساتھ قابلِ عمل کاموں میں بدلتا ہے۔'},
    definition: { ar: 'إدارة ومتابعة القرارات هي طبقة تشغيلية تربط القرار المعتمد بالمسؤول والمهلة والحالة والتصعيد داخل سجل واحد قابل للقياس والمراجعة.', en: 'Decision management and tracking connects every approved decision to an owner, due date, status, and escalation path in one measurable record.',    hi: 'निर्णय प्रबंधन और ट्रैकिंग प्रत्येक स्वीकृत निर्णय को मालिक, समयसीमा, स्थिति और एस्केलेशन पथ से एक रिकॉर्ड में जोड़ता है।', ur: 'فیصلہ جات کا نظم اور ٹریکنگ ہر منظور شدہ فیصلے کو مالک، مہلت، حالت اور تصعید کے راستے سے ایک ریکارڈ میں جوڑتا ہے۔'},
    whoFor: { ar: ['أمانة المجلس واللجان', 'الإدارة التنفيذية ووحدات المتابعة'], en: ['Board and committee secretariat', 'Executive management and follow-up teams'],    hi: ['बोर्ड और समिति सचिवालय', 'कार्यकारी प्रबंधन और फॉलो-अप टीमें'], ur: ['بورڈ اور کمیٹی سیکرٹریٹ', 'ایگزیکٹو مینجمنٹ اور فالو اپ ٹیمیں']},
    whatItSolves: { ar: ['تشتت تنفيذ القرارات بين البريد والمتابعة الفردية.', 'غياب المسؤول والمهلة بشكل منضبط.', 'ضعف الرؤية التنفيذية لحالة الإنجاز والتأخير.'], en: ['Execution scattered across email and informal follow-up.', 'No disciplined ownership or due-date control.', 'Weak executive visibility into completion and delay.'],    hi: ['निष्पादन ईमेल और अनौपचारिक फॉलो-अप में बिखर जाता है।', 'जिम्मेदारी और समयसीमा पर अनुशासन कम होता है।', 'नेतृत्व को पूर्णता और देरी पर कम दृश्यता मिलती है।'], ur: ['عمل درآمد ای میل اور غیر رسمی فالو اپ میں بکھر جاتا ہے۔', 'ذمہ داری اور مہلت پر نظم کم ہوتا ہے۔', 'قیادت کو تکمیل اور تاخیر پر کم بصیرت ملتی ہے۔']},
    howItWorks: { ar: ['اعتماد القرار داخل الاجتماع أو بعده.', 'تعيين المسؤول والأولوية وتاريخ الاستحقاق.', 'متابعة الحالة والتنبيهات والتصعيد عبر تقارير دورية.'], en: ['Approve the decision during or after the meeting.', 'Assign owner, priority, and due date.', 'Track status, alerts, and escalation through periodic reports.'],    hi: ['बैठक के दौरान या बाद में निर्णय स्वीकृत करें।', 'मालिक, प्राथमिकता और नियत तिथि तय करें।', 'रिपोर्टों में स्थिति, अलर्ट और एस्केलेशन ट्रैक करें।'], ur: ['اجلاس کے دوران یا بعد میں فیصلے کی منظوری دیں۔', 'مالک، ترجیح اور تاریخِ تکمیل متعین کریں۔', 'رپورٹس میں حالت، تنبیہات اور تصعید ٹریک کریں۔']},
    capabilities: { ar: ['تحويل القرار إلى مهمة تنفيذية.', 'تنبيهات قبل وبعد تاريخ الاستحقاق.', 'تصعيد عند التعثر أو التأخير.', 'تقارير تنفيذية للقرارات المفتوحة والمتأخرة.'], en: ['Decision-to-task conversion.', 'Alerts before and after the due date.', 'Escalation for stalled or delayed execution.', 'Executive reporting for open and overdue decisions.'],    hi: ['निर्णय से कार्य रूपांतरण।', 'नियत तिथि से पहले और बाद में अलर्ट।', 'देरी या ठहराव पर एस्केलेशन।', 'खुले और विलंबित निर्णयों की कार्यकारी रिपोर्टिंग।'], ur: ['فیصلے سے کام میں تبدیلی۔', 'تاریخِ تکمیل سے پہلے اور بعد میں تنبیہات۔', 'تاخیر یا رکاوٹ پر تصعید۔', 'کھلے اور تاخیر شدہ فیصلوں کی ایگزیکٹو رپورٹنگ۔']},
    governance: { ar: ['كل قرار يرتبط بمالك واضح ومسار متابعة موثق.', 'القيادة ترى حالة التنفيذ دون انتظار تقارير يدوية.', 'المنصة تعزز المساءلة والشفافية بين المجلس والإدارة.'], en: ['Every decision has a clear owner and documented follow-up path.', 'Leadership can see execution status without waiting for manual reports.', 'The platform strengthens accountability and transparency between the board and management.'],    hi: ['हर निर्णय का स्पष्ट मालिक और दस्तावेजित फॉलो-अप पथ होता है।', 'नेतृत्व बिना मैनुअल रिपोर्ट का इंतज़ार किए निष्पादन स्थिति देख सकता है।', 'प्लेटफ़ॉर्म बोर्ड और प्रबंधन के बीच जवाबदेही और पारदर्शिता को मजबूत करता है।'], ur: ['ہر فیصلے کا واضح مالک اور دستاویزی فالو اپ راستہ ہوتا ہے۔', 'قیادت دستی رپورٹس کے بغیر عمل درآمدی حالت دیکھ سکتی ہے۔', 'پلیٹ فارم بورڈ اور انتظامیہ کے درمیان جوابدہی اور شفافیت مضبوط کرتا ہے۔']},
    proof: { ar: ['حالة تنفيذ لحظية لكل قرار.', 'نسب إنجاز وتأخير حسب الإدارة أو اللجنة.', 'سجل تنبيهات وتصعيد مرتبط بالقرار نفسه.'], en: ['Live execution status per decision.', 'Completion and delay rates by department or committee.', 'Alert and escalation history attached to the decision itself.'],    hi: ['प्रति निर्णय लाइव निष्पादन स्थिति।', 'विभाग या समिति के अनुसार पूर्णता और देरी दरें।', 'निर्णय से जुड़ा अलर्ट और एस्केलेशन इतिहास।'], ur: ['ہر فیصلے کی لائیو عمل درآمدی حالت۔', 'شعبے یا کمیٹی کے لحاظ سے تکمیل اور تاخیر کی شرح۔', 'فیصلے سے منسلک تنبیہات اور تصعید کی ہسٹری۔']},
    outcomes: { ar: ['رؤية تنفيذية أوضح لحالة التنفيذ.', 'تقليل القرارات غير المتابعة أو المؤجلة.', 'رفع الانضباط المؤسسي في تحويل القرار إلى أثر.'], en: ['Clearer executive visibility into execution status.', 'Fewer neglected or delayed decisions.', 'Stronger institutional discipline in turning decisions into outcomes.'],    hi: ['निष्पादन स्थिति पर अधिक स्पष्ट कार्यकारी दृश्यता।', 'अनदेखे या विलंबित निर्णयों में कमी।', 'निर्णय को परिणाम में बदलने में संस्थागत अनुशासन मजबूत।'], ur: ['عمل درآمدی حالت پر زیادہ واضح انتظامی بصیرت۔', 'نظرانداز یا تاخیر شدہ فیصلوں میں کمی۔', 'فیصلے کو نتیجے میں بدلنے کے ادارہ جاتی نظم میں بہتری۔']},
    faq: { ar: [{ q: 'كيف يتحول القرار إلى مهمة؟', a: 'يرتبط القرار بسجل متابعة يتضمن المسؤول والحالة والأولوية وتاريخ الاستحقاق.' }, { q: 'هل يمكن تحديد المسؤول وتاريخ الاستحقاق؟', a: 'نعم، يتم تعيين المسؤول والمهلة الزمنية داخل مسار التنفيذ نفسه.' }, { q: 'هل توجد تنبيهات وتصعيد؟', a: 'نعم، يمكن تشغيل التنبيهات والتصعيد عند التأخير أو تعثر الإنجاز.' }, { q: 'هل توجد تقارير أداء للإدارات؟', a: 'نعم، يمكن عرض التنفيذ حسب الإدارة أو الجهة المالكة للقرار.' }], en: [{ q: 'How does a decision become a task?', a: 'The decision is linked to a follow-up record with owner, status, priority, and due date.' }, { q: 'Can an owner and due date be defined?', a: 'Yes. Responsibility and deadlines are assigned inside the execution workflow.' }, { q: 'Are alerts and escalation available?', a: 'Yes. Alerts and escalation can be triggered for delay or stalled execution.' }, { q: 'Are performance reports available for departments?', a: 'Yes. Execution can be reported by department or by decision owner.' }],    hi: [{ q: 'निर्णय कार्य में कैसे बदलता है?', a: 'निर्णय को फॉलो-अप रिकॉर्ड से जोड़ा जाता है जिसमें मालिक, स्थिति, प्राथमिकता और नियत तिथि होती है।' }, { q: 'क्या जिम्मेदार व्यक्ति और नियत तिथि तय की जा सकती है?', a: 'हाँ। जिम्मेदारी और समयसीमा उसी कार्यप्रवाह में तय की जाती है।' }, { q: 'क्या अलर्ट और एस्केलेशन उपलब्ध हैं?', a: 'हाँ। देरी या ठहराव पर ये सक्रिय किए जा सकते हैं।' }, { q: 'क्या विभागीय प्रदर्शन रिपोर्ट उपलब्ध हैं?', a: 'हाँ। निष्पादन को विभाग या निर्णय स्वामी के अनुसार देखा जा सकता है।' }], ur: [{ q: 'فیصلہ ایک کام میں کیسے بدلتا ہے؟', a: 'فیصلے کو فالو اپ ریکارڈ سے جوڑا جاتا ہے جس میں مالک، حالت، ترجیح اور تاریخِ تکمیل شامل ہو۔' }, { q: 'کیا ذمہ دار شخص اور تاریخِ تکمیل مقرر کی جا سکتی ہے؟', a: 'جی ہاں، ذمہ داری اور مہلت اسی ورک فلو میں مقرر کی جاتی ہے۔' }, { q: 'کیا تنبیہات اور تصعید موجود ہیں؟', a: 'جی ہاں، تاخیر یا رکاوٹ کی صورت میں فعال کی جا سکتی ہیں۔' }, { q: 'کیا شعبہ وار کارکردگی رپورٹس موجود ہیں؟', a: 'جی ہاں، عمل درآمد کو شعبے یا فیصلہ مالک کے مطابق دیکھا جا سکتا ہے۔' }]},
    relatedPages: ['boardManagementSystem', 'meetingMinutesEsignature', 'governanceReports'],
  },
  {
    key: 'governmentGovernance',
    eyebrow: 'industry',
    titles: { ar: 'حوكمة للجهات الحكومية', en: 'Government Governance Platform',    hi: 'सरकारी गवर्नेंस प्लेटफ़ॉर्म', ur: 'سرکاری گورننس پلیٹ فارم'},
    summary: { ar: 'بيئة حوكمة رقمية للجهات الحكومية الحساسة مع صلاحيات دقيقة، تشفير، سجل تدقيق، نسخ احتياطي، وجاهزية أفضل للامتثال المؤسسي.', en: 'A digital governance environment for sensitive government entities with granular permissions, encryption, audit trails, backup, and stronger compliance readiness.',    hi: 'उच्च-संवेदनशील सरकारी संस्थाओं के लिए डिजिटल गवर्नेंस वातावरण, जिसमें सूक्ष्म अनुमतियाँ, एन्क्रिप्शन, ऑडिट ट्रेल, बैकअप और बेहतर अनुपालन तैयारी शामिल है।', ur: 'حساس سرکاری اداروں کے لیے ڈیجیٹل گورننس ماحول جس میں باریک اجازتیں، انکرپشن، آڈٹ ٹریل، بیک اپ اور بہتر تعمیلی تیاری شامل ہے۔'},
    seoTitle: { ar: 'حوكمة للجهات الحكومية | ديوان سويت', en: 'Government Governance Platform | Diwan Suite',    hi: 'सरकारी गवर्नेंस प्लेटफ़ॉर्म | Diwan Suite', ur: 'سرکاری گورننس پلیٹ فارم | Diwan Suite'},
    seoDescription: { ar: 'حوكمة للجهات الحكومية من ديوان سويت مع صلاحيات دقيقة، تشفير أثناء النقل والتخزين، سجل تدقيق، وجاهزية أعلى للامتثال المؤسسي.', en: 'Diwan Suite government governance platform with granular permissions, encryption in transit and at rest, audit trail, and stronger compliance readiness.',    hi: 'Diwan Suite सरकारी गवर्नेंस प्लेटफ़ॉर्म सूक्ष्म अनुमतियों, एन्क्रिप्शन, ऑडिट ट्रेल और अनुपालन तैयारी का समर्थन करता है।', ur: 'Diwan Suite سرکاری گورننس پلیٹ فارم باریک اجازتوں، انکرپشن، آڈٹ ٹریل اور بہتر تعمیلی تیاری کو سپورٹ کرتا ہے۔'},
    definition: { ar: 'حوكمة للجهات الحكومية هي بيئة رقمية مضبوطة لإدارة الاجتماعات والقرارات والوثائق تحت متطلبات أعلى للسرية والتدقيق والمساءلة المؤسسية.', en: 'Government governance is a controlled digital environment for meetings, decisions, and records under higher requirements for confidentiality, auditability, and institutional accountability.',    hi: 'सरकारी गवर्नेंस एक नियंत्रित डिजिटल वातावरण है जिसमें बैठकें, निर्णय और रिकॉर्ड उच्च गोपनीयता, ऑडिट और जवाबदेही अपेक्षाओं के साथ संचालित होते हैं।', ur: 'سرکاری گورننس ایک منظم ڈیجیٹل ماحول ہے جہاں اجلاس، فیصلے اور ریکارڈ اعلیٰ رازداری، آڈٹ اور ادارہ جاتی جوابدہی کے ساتھ چلتے ہیں۔'},
    whoFor: { ar: ['الجهات الحكومية والهيئات العامة', 'أمانات المجالس واللجان الحساسة'], en: ['Government entities and public authorities', 'Sensitive board and committee secretariats'],    hi: ['सरकारी संस्थाएँ और सार्वजनिक प्राधिकरण', 'संवेदनशील बोर्ड/समिति सचिवालय'], ur: ['سرکاری ادارے اور عوامی اتھارٹیز', 'حساس بورڈ اور کمیٹی سیکرٹریٹس']},
    whatItSolves: { ar: ['صعوبة التحكم اليدوي بالوثائق الحساسة.', 'عدم كفاية الصلاحيات العامة في البيئات الحكومية.', 'ضعف الجاهزية للرقابة بدون سجل تدقيق موحد.'], en: ['Manual control of sensitive records is risky.', 'Broad permissions are not enough for government workflows.', 'Oversight readiness weakens without a unified audit trail.'],    hi: ['संवेदनशील दस्तावेज़ों का मैनुअल नियंत्रण जोखिमपूर्ण है।', 'सरकारी प्रक्रियाओं के लिए सामान्य अनुमतियाँ पर्याप्त नहीं हैं।', 'एकीकृत ऑडिट ट्रेल के बिना निगरानी तैयारी कमजोर होती है।'], ur: ['حساس دستاویزات کا دستی کنٹرول خطرناک ہے۔', 'سرکاری عمل کے لیے عمومی اجازتیں کافی نہیں ہوتیں۔', 'متحدہ آڈٹ ٹریل کے بغیر نگرانی کی تیاری کمزور ہو جاتی ہے۔']},
    howItWorks: { ar: ['ضبط الصلاحيات على مستوى الاجتماع والبند والوثيقة.', 'تشفير أثناء النقل وعند التخزين مع سجلات وصول.', 'دعم النسخ الاحتياطي والاسترجاع وسجل التدقيق المؤسسي.'], en: ['Control permissions at meeting, item, and document level.', 'Use encryption in transit and at rest with access logs.', 'Support backup, recovery, and institutional audit traceability.'],    hi: ['बैठक, आइटम और दस्तावेज़ स्तर पर अनुमतियाँ नियंत्रित करें।', 'ट्रांज़िट और एट-रेस्ट एन्क्रिप्शन के साथ एक्सेस लॉग रखें।', 'बैकअप, रिकवरी और ऑडिट ट्रेसबिलिटी का समर्थन करें।'], ur: ['اجلاس، آئٹم اور دستاویز کی سطح پر اجازتیں کنٹرول کریں۔', 'منتقلی اور اسٹوریج دونوں میں انکرپشن اور رسائی لاگز برقرار رکھیں۔', 'بیک اپ، ریکوری اور آڈٹ ٹریس ایبلٹی کو سپورٹ کریں۔']},
    capabilities: { ar: ['صلاحيات دقيقة على عدة مستويات.', 'سجل تدقيق شامل للحضور والاعتماد والوصول.', 'نسخ احتياطي واسترجاع وتوثيق زمني للعمليات.'], en: ['Granular multi-level permissions.', 'Comprehensive audit trails for access, attendance, and approvals.', 'Backup, recovery, and timestamped operational records.'],    hi: ['बहु-स्तरीय सूक्ष्म अनुमतियाँ।', 'एक्सेस, उपस्थिति और अनुमोदन के लिए पूर्ण ऑडिट ट्रेल।', 'बैकअप, रिकवरी और टाइमस्टैम्प्ड रिकॉर्ड।'], ur: ['کثیر سطحی باریک اجازتیں۔', 'رسائی، حاضری اور منظوری کے لیے مکمل آڈٹ ٹریل۔', 'بیک اپ، ریکوری اور ٹائم اسٹیمپڈ ریکارڈ۔']},
    governance: { ar: ['رفع الجاهزية للامتثال المؤسسي والرقابة الداخلية.', 'تقليل مخاطر الوصول غير المنضبط إلى الوثائق الحساسة.', 'تعزيز الثقة في مسار الاجتماعات والاعتمادات الحكومية.'], en: ['Raise readiness for institutional compliance and internal oversight.', 'Reduce the risk of uncontrolled access to sensitive records.', 'Strengthen trust in government meeting and approval workflows.'],    hi: ['संस्थागत अनुपालन और आंतरिक निगरानी के लिए तैयारी बढ़ाएँ।', 'संवेदनशील रिकॉर्ड तक अनियंत्रित पहुँच के जोखिम को कम करें।', 'सरकारी बैठक और अनुमोदन कार्यप्रवाह पर भरोसा मजबूत करें।'], ur: ['ادارہ جاتی تعمیل اور داخلی نگرانی کی تیاری بہتر بنائیں۔', 'حساس ریکارڈ تک غیر منظم رسائی کے خطرے کو کم کریں۔', 'سرکاری اجلاس اور منظوری کے ورک فلو پر اعتماد مضبوط کریں۔']},
    proof: { ar: ['تقارير صلاحيات ووصول قابلة للمراجعة.', 'سجلات نشاط موحدة للمستندات والاعتمادات.', 'مؤشرات جاهزية تشغيلية لبيئات رقابية حساسة.'], en: ['Reviewable permission and access reports.', 'Unified activity logs for documents and approvals.', 'Operational readiness indicators for sensitive regulatory environments.'],    hi: ['समीक्षा योग्य अनुमति और एक्सेस रिपोर्ट।', 'दस्तावेज़ और अनुमोदनों के लिए एकीकृत गतिविधि लॉग।', 'संवेदनशील विनियमित वातावरणों के लिए परिचालन तत्परता संकेतक।'], ur: ['جائزہ کے قابل اجازت اور رسائی رپورٹس۔', 'دستاویزات اور منظوریوں کے لیے متحدہ سرگرمی لاگز۔', 'حساس منظم ماحول کے لیے آپریشنل تیاری کے اشارے۔']},
    outcomes: { ar: ['جاهزية أعلى للتدقيق والامتثال.', 'خفض مخاطر التعارض في الصلاحيات والوصول.', 'ثقة مؤسسية أكبر في إدارة الاجتماعات الحكومية.'], en: ['Stronger readiness for audit and compliance.', 'Lower risk of conflicting access and permission exposure.', 'Greater institutional trust in government meeting governance.'],    hi: ['ऑडिट और अनुपालन के लिए बेहतर तैयारी।', 'अनुमतियों और एक्सेस विवाद के जोखिम में कमी।', 'सरकारी बैठकों के शासन पर संस्थागत विश्वास में वृद्धि।'], ur: ['آڈٹ اور تعمیل کے لیے بہتر تیاری۔', 'اجازتوں اور رسائی کے تنازع کے خطرے میں کمی۔', 'سرکاری اجلاسوں کی گورننس پر ادارہ جاتی اعتماد میں اضافہ۔']},
    faq: { ar: [{ q: 'هل يدعم البيئات الحكومية الحساسة؟', a: 'نعم، يدعم التحكم الدقيق في الصلاحيات والوصول ضمن بيئات تتطلب سرية وتشددًا رقابيًا أعلى.' }, { q: 'هل توجد صلاحيات دقيقة؟', a: 'نعم، يمكن ضبط الصلاحيات على مستوى الاجتماع والبند والوثيقة.' }, { q: 'هل يوجد سجل تدقيق؟', a: 'نعم، يتم الاحتفاظ بسجل نشاط واعتماد يساعد في المراجعة والحوكمة.' }, { q: 'هل توجد تقارير امتثال جاهزة؟', a: 'المنصة تدعم تقارير ولوحات متابعة تساعد الجهات على الاستعداد للرقابة والامتثال المؤسسي.' }], en: [{ q: 'Does it support sensitive government environments?', a: 'Yes. It supports controlled access and governance workflows suited for high-sensitivity public environments.' }, { q: 'Are granular permissions available?', a: 'Yes. Permissions can be controlled at meeting, item, and document level.' }, { q: 'Is there an audit trail?', a: 'Yes. Activity and approval records are retained to support governance review.' }, { q: 'Are compliance-ready reports available?', a: 'The platform supports reporting and dashboards that improve institutional oversight readiness.' }],    hi: [{ q: 'क्या यह संवेदनशील सरकारी वातावरणों के लिए उपयुक्त है?', a: 'हाँ। यह उच्च-संवेदनशील सार्वजनिक वातावरणों के लिए नियंत्रित एक्सेस और गवर्नेंस वर्कफ़्लो का समर्थन करता है।' }, { q: 'क्या सूक्ष्म अनुमतियाँ उपलब्ध हैं?', a: 'हाँ। अनुमतियाँ बैठक, आइटम और दस्तावेज़ स्तर पर नियंत्रित की जा सकती हैं।' }, { q: 'क्या ऑडिट ट्रेल है?', a: 'हाँ। गतिविधि और अनुमोदन रिकॉर्ड गवर्नेंस समीक्षा में मदद करते हैं।' }, { q: 'क्या अनुपालन रिपोर्ट उपलब्ध हैं?', a: 'प्लेटफ़ॉर्म रिपोर्टिंग और डैशबोर्ड के माध्यम से अनुपालन तैयारी को समर्थन देता है।' }], ur: [{ q: 'کیا یہ حساس سرکاری ماحول کے لیے موزوں ہے؟', a: 'جی ہاں، یہ اعلیٰ حساسیت والے عوامی ماحول کے لیے کنٹرولڈ رسائی اور گورننس ورک فلو فراہم کرتا ہے۔' }, { q: 'کیا باریک اجازتیں موجود ہیں؟', a: 'جی ہاں، اجازتیں اجلاس، آئٹم اور دستاویز کی سطح پر کنٹرول کی جا سکتی ہیں۔' }, { q: 'کیا آڈٹ ٹریل موجود ہے؟', a: 'جی ہاں، سرگرمی اور منظوری کے ریکارڈ گورننس جائزے میں مدد دیتے ہیں۔' }, { q: 'کیا تعمیلی رپورٹس دستیاب ہیں؟', a: 'پلیٹ فارم رپورٹنگ اور ڈیش بورڈز کے ذریعے تعمیل کی تیاری کو سپورٹ کرتا ہے۔' }]},
    relatedPages: ['boardManagementSystem', 'securityCompliance', 'governanceReports'],
  },
  {
    key: 'listedCompaniesGovernance',
    eyebrow: 'industry',
    titles: { ar: 'حوكمة للشركات المدرجة', en: 'Governance for Listed Companies',    hi: 'सूचीबद्ध कंपनियों के लिए गवर्नेंस', ur: 'لسٹڈ کمپنیوں کے لیے گورننس'},
    summary: { ar: 'مسار حوكمي يدعم محاضر المجلس واللجان، سرعة الاعتماد، متابعة التنفيذ، ورفع الشفافية والمساءلة داخل الشركات المدرجة.', en: 'A governance workflow for listed companies that supports board and committee minutes, faster approvals, execution tracking, and stronger transparency and accountability.',    hi: 'सूचीबद्ध कंपनियों के लिए गवर्नेंस वर्कफ़्लो जो बोर्ड/समिति मिनट्स, तेज अनुमोदन, निष्पादन ट्रैकिंग और अधिक पारदर्शिता का समर्थन करता है।', ur: 'لسٹڈ کمپنیوں کے لیے گورننس ورک فلو جو بورڈ و کمیٹی محاضر، تیز منظوری، عمل درآمدی ٹریکنگ اور زیادہ شفافیت کو سپورٹ کرتا ہے۔'},
    seoTitle: { ar: 'حوكمة للشركات المدرجة | ديوان سويت', en: 'Governance for Listed Companies | Diwan Suite',    hi: 'सूचीबद्ध कंपनियों के लिए गवर्नेंस | Diwan Suite', ur: 'لسٹڈ کمپنیوں کے لیے گورننس | Diwan Suite'},
    seoDescription: { ar: 'حوكمة للشركات المدرجة من ديوان سويت لدعم محاضر المجلس واللجان، سرعة الاعتماد، متابعة التنفيذ، ورفع الشفافية والمساءلة المؤسسية.', en: 'Diwan Suite governance for listed companies with board and committee minutes, faster approvals, execution tracking, and stronger transparency and accountability.',    hi: 'Diwan Suite सूचीबद्ध कंपनियों के लिए गवर्नेंस, जिसमें मिनट्स, तेज अनुमोदन, निष्पादन ट्रैकिंग और पारदर्शिता शामिल है।', ur: 'Diwan Suite لسٹڈ کمپنیوں کے لیے گورننس، جس میں محاضر، تیز منظوری، عمل درآمدی ٹریکنگ اور شفافیت شامل ہے۔'},
    definition: { ar: 'حوكمة الشركات المدرجة تتطلب مساراً موثقاً يربط بين الاجتماع والمحضر والقرار والتنفيذ بحيث يبقى القرار قابلاً للتتبع والمراجعة والقياس.', en: 'Governance for listed companies requires a documented path that connects meetings, minutes, decisions, and execution so that outcomes remain traceable, reviewable, and measurable.',    hi: 'सूचीबद्ध कंपनियों के लिए गवर्नेंस में बैठक, मिनट्स, निर्णय और निष्पादन को जोड़ने वाला दस्तावेजित मार्ग आवश्यक है ताकि परिणाम ट्रैसेबल और मापनीय रहें।', ur: 'لسٹڈ کمپنیوں کی گورننس کے لیے ایک دستاویزی راستہ درکار ہوتا ہے جو اجلاس، محضر، فیصلہ اور عمل درآمد کو جوڑ کر نتائج کو قابلِ ٹریک اور قابلِ جائزہ بناتا ہے۔'},
    whoFor: { ar: ['الشركات المدرجة وأمانات المجالس', 'لجان المراجعة والترشيحات والمخاطر'], en: ['Listed companies and board secretariats', 'Audit, nomination, and risk committees'],    hi: ['सूचीबद्ध कंपनियाँ और बोर्ड सचिवालय', 'ऑडिट, नामांकन और जोखिम समितियाँ'], ur: ['لسٹڈ کمپنیاں اور بورڈ سیکرٹریٹس', 'آڈٹ، نامزدگی اور رسک کمیٹیاں']},
    whatItSolves: { ar: ['بطء الاعتماد ينعكس على سرعة القرار والتنفيذ.', 'المحاضر والقرارات تتوزع بين ملفات ورسائل ومراجعات منفصلة.', 'يصعب قياس الالتزام والتنفيذ والشفافية عبر سجلات مشتتة.'], en: ['Slow approvals delay decision flow and execution.', 'Minutes and decisions become fragmented across files, emails, and manual reviews.', 'Scattered records make compliance, execution, and transparency difficult to measure.'],    hi: ['धीमी स्वीकृतियाँ निर्णय और निष्पादन को धीमा करती हैं।', 'मिनट्स और निर्णय फ़ाइलों, ईमेल और मैनुअल समीक्षा में बिखर जाते हैं।', 'बिखरे रिकॉर्ड अनुपालन, निष्पादन और पारदर्शिता को मापना कठिन बनाते हैं।'], ur: ['سست منظوری فیصلے اور عمل درآمد کو تاخیر کا شکار بناتی ہے۔', 'محاضر اور فیصلے فائلوں، ای میلز اور دستی جائزوں میں بکھر جاتے ہیں۔', 'بکھرا ہوا ریکارڈ تعمیل، عمل درآمد اور شفافیت کی پیمائش مشکل بنا دیتا ہے۔']},
    howItWorks: { ar: ['إعداد الاجتماع والمحضر والوثائق داخل مسار موحد.', 'اعتماد المحضر والقرارات بمسارات واضحة وموثقة.', 'تحويل المخرجات إلى متابعة وتقارير للقيادة.'], en: ['Prepare meetings, minutes, and documents in one structured flow.', 'Approve minutes and decisions through clear documented routes.', 'Turn outputs into follow-up and leadership reporting.'],    hi: ['बैठक, मिनट्स और दस्तावेज़ एक संरचित प्रवाह में तैयार करें।', 'मिनट्स और निर्णयों को स्पष्ट दस्तावेजित मार्ग से स्वीकृत करें।', 'आउटपुट को फॉलो-अप और नेतृत्व रिपोर्टिंग में बदलें।'], ur: ['اجلاس، محاضر اور دستاویزات کو ایک منظم فلو میں تیار کریں۔', 'محاضر اور فیصلوں کو واضح دستاویزی راستے سے منظور کریں۔', 'نتائج کو فالو اپ اور قیادتی رپورٹنگ میں بدلیں۔']},
    capabilities: { ar: ['محاضر قابلة للاعتماد والاسترجاع.', 'تتبع قرارات المجلس واللجان حتى التنفيذ.', 'تقارير تنفيذية تدعم الشفافية والمساءلة.'], en: ['Approval-ready and retrievable minutes.', 'Tracking of board and committee decisions through execution.', 'Executive reporting that supports transparency and accountability.'],    hi: ['अनुमोदन-तैयार और खोज योग्य मिनट्स।', 'बोर्ड और समिति निर्णयों का निष्पादन तक ट्रैकिंग।', 'पारदर्शिता और जवाबदेही को सहारा देने वाली कार्यकारी रिपोर्टिंग।'], ur: ['منظوری کے لیے تیار اور قابلِ بازیافت محاضر۔', 'بورڈ اور کمیٹی فیصلوں کی عمل درآمد تک ٹریکنگ۔', 'شفافیت اور جوابدہی کو سہارا دینے والی ایگزیکٹو رپورٹنگ۔']},
    governance: { ar: ['رفع الشفافية أمام المجلس واللجان والقيادة التنفيذية.', 'تسهيل إثبات الانضباط والالتزام المؤسسي.', 'تقوية قابلية المراجعة واسترجاع السجل الحوكمي.'], en: ['Improve transparency for boards, committees, and executive leadership.', 'Make institutional discipline and compliance easier to evidence.', 'Strengthen auditability and retrieval of governance records.'],    hi: ['बोर्ड, समितियों और नेतृत्व के लिए पारदर्शिता बढ़ाएँ।', 'संस्थागत अनुशासन और अनुपालन को प्रमाणित करना आसान बनाएं।', 'गवर्नेंस रिकॉर्ड की ऑडिटेबिलिटी और पुनर्प्राप्ति मजबूत करें।'], ur: ['بورڈ، کمیٹیوں اور قیادت کے لیے شفافیت بہتر بنائیں۔', 'ادارہ جاتی نظم و تعمیل کو ثابت کرنا آسان بنائیں۔', 'گورننس ریکارڈ کی آڈٹ ایبلٹی اور بازیافت مضبوط کریں۔']},
    proof: { ar: ['محاضر مجلس ولجان مرتبطة بالقرارات.', 'تقارير التزام وتنفيذ قابلة للعرض للقيادة.', 'سجل موحد يسهل استرجاعه ومراجعته.'], en: ['Board and committee minutes linked to decisions.', 'Compliance and execution reports visible to leadership.', 'A unified record that is easier to retrieve and review.'],    hi: ['निर्णयों से जुड़े बोर्ड और समिति मिनट्स।', 'नेतृत्व को दिखने वाली अनुपालन और निष्पादन रिपोर्ट।', 'एकीकृत रिकॉर्ड जिसे आसानी से खोजा और समीक्षा किया जा सके।'], ur: ['فیصلوں سے منسلک بورڈ اور کمیٹی محاضر۔', 'قیادت کے لیے قابلِ مشاہدہ تعمیل اور عمل درآمد رپورٹس۔', 'متحدہ ریکارڈ جسے آسانی سے حاصل اور جائزہ لیا جا سکے۔']},
    outcomes: { ar: ['رفع الانضباط الحوكمي للشركات المدرجة.', 'تسريع الاعتماد دون فقدان الشفافية.', 'تحسين رؤية القيادة لحالة التنفيذ والالتزام.'], en: ['Stronger governance discipline for listed companies.', 'Faster approvals without losing transparency.', 'Better leadership visibility into execution and compliance.'],    hi: ['सूचीबद्ध कंपनियों के लिए अधिक मजबूत गवर्नेंस अनुशासन।', 'पारदर्शिता खोए बिना तेज अनुमोदन।', 'निष्पादन और अनुपालन पर बेहतर नेतृत्व दृश्यता।'], ur: ['لسٹڈ کمپنیوں کے لیے زیادہ مضبوط گورننس نظم۔', 'شفافیت کھوئے بغیر تیز منظوری۔', 'عمل درآمد اور تعمیل پر بہتر قیادتی بصیرت۔']},
    faq: { ar: [{ q: 'كيف يساعد في الحوكمة المؤسسية؟', a: 'يربط الاجتماعات والمحاضر والقرارات والتنفيذ ضمن سجل موثق يسهل قياسه ومراجعته.' }, { q: 'هل يدعم محاضر المجلس واللجان؟', a: 'نعم، يدعم إعداد المحاضر واعتمادها وربطها بالقرارات والمرفقات.' }, { q: 'هل يعزز الشفافية والمتابعة؟', a: 'نعم، عبر سجلات واضحة ولوحات متابعة وربط القرار بالتنفيذ.' }, { q: 'هل يمكن قياس الالتزام والتنفيذ؟', a: 'نعم، من خلال تقارير ولوحات مؤشرات لحالة التنفيذ والالتزام.' }], en: [{ q: 'How does it help institutional governance?', a: 'It connects meetings, minutes, decisions, and execution in one documented operating record.' }, { q: 'Does it support board and committee minutes?', a: 'Yes. Minutes can be prepared, approved, and linked to decisions and attachments.' }, { q: 'Does it improve transparency and follow-up?', a: 'Yes. It provides clear records, follow-up dashboards, and decision-to-execution linkage.' }, { q: 'Can compliance and execution be measured?', a: 'Yes. Reporting and dashboards can show execution and commitment status.' }],    hi: [{ q: 'यह संस्थागत गवर्नेंस में कैसे मदद करता है?', a: 'यह बैठकों, मिनट्स, निर्णयों और निष्पादन को एक दस्तावेजित संचालन रिकॉर्ड में जोड़ता है।' }, { q: 'क्या यह बोर्ड और समिति मिनट्स का समर्थन करता है?', a: 'हाँ। मिनट्स तैयार, स्वीकृत और निर्णयों से जोड़े जा सकते हैं।' }, { q: 'क्या यह पारदर्शिता और फॉलो-अप बढ़ाता है?', a: 'हाँ। यह स्पष्ट रिकॉर्ड, डैशबोर्ड और निर्णय-से-निष्पादन लिंक देता है।' }, { q: 'क्या अनुपालन और निष्पादन को मापा जा सकता है?', a: 'हाँ। रिपोर्टिंग और डैशबोर्ड से स्थिति मापी जा सकती है।' }], ur: [{ q: 'یہ ادارہ جاتی گورننس میں کیسے مدد کرتا ہے؟', a: 'یہ اجلاس، محاضر، فیصلوں اور عمل درآمد کو ایک دستاویزی آپریٹنگ ریکارڈ میں جوڑتا ہے۔' }, { q: 'کیا یہ بورڈ اور کمیٹی محاضر کو سپورٹ کرتا ہے؟', a: 'جی ہاں، محاضر تیار، منظور اور فیصلوں سے منسلک کیے جا سکتے ہیں۔' }, { q: 'کیا یہ شفافیت اور فالو اپ بہتر بناتا ہے؟', a: 'جی ہاں، واضح ریکارڈ، ڈیش بورڈز اور فیصلہ تا عمل درآمد ربط فراہم کرتا ہے۔' }, { q: 'کیا تعمیل اور عمل درآمد کو ماپا جا سکتا ہے؟', a: 'جی ہاں، رپورٹس اور ڈیش بورڈز کے ذریعے حالت دیکھی جا سکتی ہے۔' }]},
    relatedPages: ['boardManagementSystem', 'decisionTracking', 'meetingMinutesEsignature'],
  },
  {
    key: 'bankingGovernance',
    eyebrow: 'industry',
    titles: { ar: 'حوكمة للبنوك والقطاع المالي', en: 'Governance for Banks & Financial Sector',    hi: 'बैंकों और वित्तीय क्षेत्र के लिए गवर्नेंस', ur: 'بینکوں اور مالیاتی شعبے کے لیے گورننس'},
    summary: { ar: 'مسار حوكمي مناسب للبنوك والقطاع المالي حيث السرية العالية، مسارات الاعتماد الدقيقة، سجل التدقيق، والتقارير التنفيذية الموثوقة.', en: 'A governance workflow for banks and the financial sector where high confidentiality, disciplined approvals, audit traceability, and executive reporting are essential.',    hi: 'बैंकों और वित्तीय क्षेत्र के लिए गवर्नेंस वर्कफ़्लो जिसमें उच्च गोपनीयता, अनुशासित अनुमोदन, ऑडिट ट्रेसबिलिटी और रिपोर्टिंग शामिल है।', ur: 'بینکوں اور مالیاتی شعبے کے لیے گورننس ورک فلو جس میں اعلیٰ رازداری، منظم منظوری، آڈٹ ٹریس ایبلٹی اور رپورٹنگ شامل ہے۔'},
    seoTitle: { ar: 'حوكمة للبنوك والقطاع المالي | ديوان سويت', en: 'Governance for Banks & Financial Sector | Diwan Suite',    hi: 'बैंकों और वित्तीय क्षेत्र के लिए गवर्नेंस | Diwan Suite', ur: 'بینکوں اور مالیاتی شعبے کے لیے گورننس | Diwan Suite'},
    seoDescription: { ar: 'حوكمة للبنوك والقطاع المالي من ديوان سويت لدعم السرية، الاعتمادات، سجل التدقيق، والتقارير التنفيذية داخل بيئات مالية منظمة.', en: 'Diwan Suite governance for banks and financial sector with stronger confidentiality, approval workflows, audit trail, and executive reporting.',    hi: 'Diwan Suite बैंकों और वित्तीय क्षेत्र के लिए गोपनीयता, अनुमोदन वर्कफ़्लो, ऑडिट ट्रेल और कार्यकारी रिपोर्टिंग का समर्थन करता है।', ur: 'Diwan Suite بینکوں اور مالیاتی شعبے کے لیے رازداری، منظوری ورک فلو، آڈٹ ٹریل اور ایگزیکٹو رپورٹنگ فراہم کرتا ہے۔'},
    definition: { ar: 'حوكمة للبنوك والقطاع المالي هي بيئة رقمية تضبط الاجتماعات والاعتمادات والمحاضر والقرارات ضمن معايير أعلى للسرية والرقابة والانضباط التنفيذي.', en: 'Governance for banks and the financial sector is a digital operating environment for meetings, approvals, minutes, and decisions under stricter confidentiality and control expectations.',    hi: 'बैंकों और वित्तीय क्षेत्र के लिए गवर्नेंस एक डिजिटल संचालन वातावरण है जो बैठकों, अनुमोदनों, मिनट्स और निर्णयों को उच्च गोपनीयता व नियंत्रण के साथ संचालित करता है।', ur: 'بینکوں اور مالیاتی شعبے کے لیے گورننس ایک ڈیجیٹل آپریٹنگ ماحول ہے جو اجلاس، منظوری، محاضر اور فیصلوں کو اعلیٰ رازداری اور کنٹرول کے ساتھ چلاتا ہے۔'},
    whoFor: { ar: ['البنوك والمؤسسات المالية', 'أمانات المجالس واللجان الرقابية'], en: ['Banks and financial institutions', 'Board and control committee secretariats'],    hi: ['बैंक और वित्तीय संस्थाएँ', 'बोर्ड और नियंत्रण समितियों के सचिवालय'], ur: ['بینک اور مالیاتی ادارے', 'بورڈ اور کنٹرول کمیٹی سیکرٹریٹس']},
    whatItSolves: { ar: ['المستندات الحساسة تتطلب ضبطاً أعلى من الأدوات العامة.', 'مسارات الاعتماد غير المنضبطة تضعف الثقة وسرعة الإنجاز.', 'القيادة تحتاج رؤية تنفيذية واضحة دون التضحية بالرقابة.'], en: ['Sensitive records require stronger control than general-purpose tools.', 'Undisciplined approval routes weaken trust and speed.', 'Leadership needs visibility without sacrificing control.'],    hi: ['संवेदनशील रिकॉर्ड सामान्य उपकरणों से अधिक नियंत्रण मांगते हैं।', 'अव्यवस्थित अनुमोदन मार्ग भरोसा और गति को कमजोर करते हैं।', 'नेतृत्व को नियंत्रण खोए बिना दृश्यता चाहिए।'], ur: ['حساس ریکارڈ عمومی ٹولز سے زیادہ مضبوط کنٹرول مانگتے ہیں۔', 'غیر منظم منظوری راستے اعتماد اور رفتار کو کمزور کرتے ہیں۔', 'قیادت کو کنٹرول برقرار رکھتے ہوئے بصیرت چاہیے۔']},
    howItWorks: { ar: ['تنظيم الاعتماد والمحاضر والقرارات ضمن مسارات دقيقة.', 'دعم السرية والحساسية العالية للبيانات والوثائق.', 'توفير تقارير تنفيذية تساعد على الرقابة والقياس.'], en: ['Organize approvals, minutes, and decisions through controlled workflows.', 'Support highly sensitive records and confidential governance operations.', 'Provide executive reporting for oversight and measurement.'],    hi: ['नियंत्रित वर्कफ़्लो के माध्यम से अनुमोदन, मिनट्स और निर्णयों को व्यवस्थित करें।', 'उच्च-संवेदनशील रिकॉर्ड और गोपनीय गवर्नेंस संचालन का समर्थन करें।', 'निगरानी और मापन हेतु कार्यकारी रिपोर्टिंग दें।'], ur: ['منظم ورک فلو کے ذریعے منظوری، محاضر اور فیصلوں کو ترتیب دیں۔', 'حساس ریکارڈز اور خفیہ گورننس آپریشنز کو سپورٹ کریں۔', 'نگرانی اور پیمائش کے لیے ایگزیکٹو رپورٹنگ فراہم کریں۔']},
    capabilities: { ar: ['مسارات اعتماد منضبطة.', 'سجل تدقيق ووصول واضح.', 'تقارير تنفيذية وقيادية.', 'استرجاع سريع للمحاضر والقرارات والوثائق.'], en: ['Disciplined approval workflows.', 'Clear audit and access records.', 'Executive and leadership reporting.', 'Fast retrieval of minutes, decisions, and records.'],    hi: ['अनुशासित अनुमोदन वर्कफ़्लो।', 'स्पष्ट ऑडिट और एक्सेस रिकॉर्ड।', 'कार्यकारी और नेतृत्व रिपोर्टिंग।', 'मिनट्स, निर्णय और दस्तावेज़ों की तेज पुनर्प्राप्ति।'], ur: ['منظم منظوری ورک فلو۔', 'واضح آڈٹ اور رسائی ریکارڈ۔', 'ایگزیکٹو اور قیادتی رپورٹنگ۔', 'محاضر، فیصلوں اور دستاویزات کی تیز بازیافت۔']},
    governance: { ar: ['رفع الثقة في إدارة الاجتماعات داخل البيئات المالية الحساسة.', 'تسهيل المراجعة والرقابة عبر سجل واضح.', 'تقوية الانضباط في الاعتماد والتنفيذ.'], en: ['Strengthen trust in meeting governance inside sensitive financial environments.', 'Support oversight through a clear reviewable record.', 'Increase discipline in approvals and execution.'],    hi: ['संवेदनशील वित्तीय वातावरणों में बैठक गवर्नेंस पर भरोसा मजबूत करें।', 'स्पष्ट समीक्षा योग्य रिकॉर्ड के माध्यम से निगरानी को समर्थन दें।', 'अनुमोदन और निष्पादन अनुशासन बढ़ाएँ।'], ur: ['حساس مالیاتی ماحول میں اجلاس گورننس پر اعتماد مضبوط کریں۔', 'واضح قابلِ جائزہ ریکارڈ کے ذریعے نگرانی کو سپورٹ کریں۔', 'منظوری اور عمل درآمد میں نظم بڑھائیں۔']},
    proof: { ar: ['محاضر وقرارات ضمن سجل موحد.', 'تقارير تنفيذية ومؤشرات للقيادة.', 'سجل تدقيق قابل للاسترجاع والمراجعة.'], en: ['Minutes and decisions in one unified record.', 'Executive reports and leadership indicators.', 'Audit trail ready for retrieval and review.'],    hi: ['एकीकृत रिकॉर्ड में मिनट्स और निर्णय।', 'कार्यकारी रिपोर्ट और नेतृत्व संकेतक।', 'पुनर्प्राप्ति और समीक्षा के लिए ऑडिट ट्रेल।'], ur: ['متحدہ ریکارڈ میں محاضر اور فیصلے۔', 'ایگزیکٹو رپورٹس اور قیادتی اشارے۔', 'بازیافت اور جائزے کے لیے آڈٹ ٹریل۔']},
    outcomes: { ar: ['ثقة أعلى في مسار الحوكمة المالية.', 'ضبط أفضل للسرية والاعتماد.', 'تقارير تنفيذية أوضح للقيادة العليا.'], en: ['Higher trust in financial governance workflows.', 'Better control over confidentiality and approvals.', 'Clearer executive reporting for leadership.'],    hi: ['वित्तीय गवर्नेंस वर्कफ़्लो पर अधिक भरोसा।', 'गोपनीयता और अनुमोदनों पर बेहतर नियंत्रण।', 'नेतृत्व के लिए अधिक स्पष्ट रिपोर्टिंग।'], ur: ['مالیاتی گورننس ورک فلو پر زیادہ اعتماد۔', 'رازداری اور منظوریوں پر بہتر کنٹرول۔', 'قیادت کے لیے زیادہ واضح رپورٹنگ۔']},
    faq: { ar: [{ q: 'هل يناسب البنوك والقطاع المالي؟', a: 'نعم، صُمم لدعم البيئات التي تتطلب حساسية أعلى للبيانات وانضباطًا أكبر في الاعتماد.' }, { q: 'كيف يتعامل مع السرية والحساسية العالية؟', a: 'من خلال مسارات وصول واعتماد واضحة، وسجل نشاط، وتنظيم أفضل للمرفقات والوثائق.' }, { q: 'هل توجد مسارات اعتماد وتدقيق؟', a: 'نعم، يمكن اعتماد المحاضر والقرارات داخل مسار موثق وقابل للمراجعة.' }, { q: 'هل يدعم التقارير التنفيذية والامتثال؟', a: 'نعم، يدعم تقارير ولوحات متابعة تساعد القيادة على الرقابة وقياس التنفيذ.' }], en: [{ q: 'Is it suitable for banks and the financial sector?', a: 'Yes. It is designed for environments that require stronger data sensitivity and tighter approval discipline.' }, { q: 'How does it handle high confidentiality and sensitivity?', a: 'Through controlled access and approval flows, activity records, and better document handling.' }, { q: 'Are approval and audit workflows available?', a: 'Yes. Minutes and decisions can move through a documented and reviewable workflow.' }, { q: 'Does it support executive reporting and compliance?', a: 'Yes. Reporting and dashboards help leadership oversee execution and readiness.' }],    hi: [{ q: 'क्या यह बैंकों और वित्तीय क्षेत्र के लिए उपयुक्त है?', a: 'हाँ। यह उन वातावरणों के लिए तैयार है जहाँ डेटा संवेदनशीलता और अनुमोदन अनुशासन अधिक महत्वपूर्ण हैं।' }, { q: 'यह उच्च गोपनीयता और संवेदनशीलता को कैसे संभालता है?', a: 'नियंत्रित एक्सेस, अनुमोदन मार्ग, गतिविधि रिकॉर्ड और बेहतर दस्तावेज़ प्रबंधन के माध्यम से।' }, { q: 'क्या अनुमोदन और ऑडिट वर्कफ़्लो उपलब्ध हैं?', a: 'हाँ। मिनट्स और निर्णय दस्तावेजित और समीक्षा योग्य मार्ग से गुजरते हैं।' }, { q: 'क्या यह कार्यकारी रिपोर्टिंग और अनुपालन का समर्थन करता है?', a: 'हाँ। रिपोर्ट और डैशबोर्ड नेतृत्व को निष्पादन और तैयारी पर निगरानी देते हैं।' }], ur: [{ q: 'کیا یہ بینکوں اور مالیاتی شعبے کے لیے موزوں ہے؟', a: 'جی ہاں، یہ ایسے ماحول کے لیے تیار کیا گیا ہے جہاں ڈیٹا کی حساسیت اور منظوری کا نظم زیادہ اہم ہو۔' }, { q: 'یہ اعلیٰ رازداری اور حساسیت کو کیسے سنبھالتا ہے؟', a: 'کنٹرولڈ رسائی، منظوری راستے، سرگرمی ریکارڈ اور بہتر دستاویزی نظم کے ذریعے۔' }, { q: 'کیا منظوری اور آڈٹ ورک فلو موجود ہیں؟', a: 'جی ہاں، محاضر اور فیصلے دستاویزی اور قابلِ جائزہ راستے سے گزرتے ہیں۔' }, { q: 'کیا یہ ایگزیکٹو رپورٹنگ اور تعمیل کو سپورٹ کرتا ہے؟', a: 'جی ہاں، رپورٹس اور ڈیش بورڈز قیادت کو عمل درآمد اور تیاری پر نظر دیتے ہیں۔' }]},
    relatedPages: ['boardManagementSystem', 'securityCompliance', 'governanceReports'],
  },
]

export const phase3bPageCopy: Record<LangCode, Record<Phase3BPageKey, InternalPageCopy>> = {
  ar: {} as Record<Phase3BPageKey, InternalPageCopy>,
  en: {} as Record<Phase3BPageKey, InternalPageCopy>,
  hi: {} as Record<Phase3BPageKey, InternalPageCopy>,
  ur: {} as Record<Phase3BPageKey, InternalPageCopy>,
}

for (const lang of Object.keys(labels) as LangCode[]) {
  for (const page of pages) {
    phase3bPageCopy[lang][page.key] = copy(lang, page)
  }
}
