import type { LangCode } from './types'
import type { InternalPageCopy, InternalPageFaqItem } from './extra'

type Phase3CPageKey =
  | 'aiGovernanceDecisionSupport'
  | 'attendanceQuorumQr'
  | 'governanceReportsDashboards'
  | 'integrationsBoardGovernance'
  | 'governanceSecurityCompliance'
  | 'roiBoardGovernance'
  | 'implementationSupportTraining'

type LString = Record<LangCode, string>
type LList = Record<LangCode, string[]>
type LFaq = Record<LangCode, InternalPageFaqItem[]>

type Labels = {
  platform: string
  trust: string
  support: string
  direct: string
  problems: string
  solutionTitle: string
  capabilities: string
  workflow: string
  governance: string
  proof: string
  outcomes: string
  executive: string
}

const labels: Record<LangCode, Labels> = {
  ar: { platform: 'المنصة والعمليات', trust: 'الأمن والامتثال', support: 'التطبيق والدعم', direct: 'لمحة سريعة', problems: 'تحديات تشغيلية قائمة', solutionTitle: 'كيف يعالجها ديوان سويت', capabilities: 'قدرات أساسية', workflow: 'كيف يعمل المسار', governance: 'الأثر الحوكمي والرقابي', proof: 'شواهد تشغيلية', outcomes: 'مخرجات تنفيذية قابلة للقياس', executive: 'ملخص تنفيذي' },
  en: { platform: 'Platform & Operations', trust: 'Security & Compliance', support: 'Implementation & Support', direct: 'Quick overview', problems: 'Current operational pain', solutionTitle: 'How Diwan Suite addresses it', capabilities: 'Key capabilities', workflow: 'How the workflow operates', governance: 'Governance, compliance, and audit impact', proof: 'Operational proof points', outcomes: 'Executive outcomes', executive: 'Executive Summary' },

  hi: { platform: 'प्लेटफ़ॉर्म और संचालन', trust: 'सुरक्षा और अनुपालन', support: 'कार्यान्वयन और सहायता', direct: 'त्वरित परिचय', problems: 'वर्तमान परिचालन चुनौतियाँ', solutionTitle: 'Diwan Suite इसे कैसे संभालता है', capabilities: 'मुख्य क्षमताएँ', workflow: 'वर्कफ़्लो कैसे चलता है', governance: 'गवर्नेंस, अनुपालन और ऑडिट प्रभाव', proof: 'ऑपरेशनल प्रमाण', outcomes: 'कार्यकारी परिणाम', executive: 'कार्यकारी सार' },
  ur: { platform: 'پلیٹ فارم اور آپریشنز', trust: 'سیکیورٹی اور تعمیل', support: 'نفاذ اور سپورٹ', direct: 'مختصر جائزہ', problems: 'موجودہ آپریشنل چیلنجز', solutionTitle: 'Diwan Suite مسئلہ کیسے حل کرتا ہے', capabilities: 'اہم صلاحیتیں', workflow: 'ورک فلو کیسے چلتا ہے', governance: 'گورننس، تعمیل اور آڈٹ اثرات', proof: 'عملی شواہد', outcomes: 'انتظامی نتائج', executive: 'ایگزیکٹو خلاصہ' },

}

type Def = {
  key: Phase3CPageKey
  eyebrow: 'platform' | 'trust' | 'support'
  titles: LString
  summary: LString
  seoTitle: LString
  seoDescription: LString
  definition: LString
  whoFor: LList
  whatItSolves: LList
  howItWorks: LList
  capabilities: LList
  governance: LList
  proof: LList
  outcomes: LList
  faq: LFaq
  relatedPages: string[]
}

function faqMap(ar: [string, string][], en: [string, string][], hi: [string, string][], ur: [string, string][]): LFaq {
  const build = (items: [string, string][]): InternalPageFaqItem[] => items.map(([q, a]) => ({ q, a }))
  return { ar: build(ar), en: build(en), hi: build(hi), ur: build(ur) }
}

function copy(lang: LangCode, page: Def): InternalPageCopy {
  const t = labels[lang]
  const eyebrow = page.eyebrow === 'trust' ? t.trust : page.eyebrow === 'support' ? t.support : t.platform
  return {
    eyebrow,
    title: page.titles[lang],
    summary: page.summary[lang],
    seoTitle: page.seoTitle[lang],
    seoDescription: page.seoDescription[lang],
    executiveSummary: t.executive,
    definition: page.definition[lang],
    whoFor: page.whoFor[lang],
    whatItSolves: page.whatItSolves[lang],
    howItWorks: page.howItWorks[lang],
    faq: page.faq[lang],
    relatedPages: page.relatedPages,
    sections: [
      { id: 'problems', title: t.problems, body: [page.summary[lang]], bullets: page.whatItSolves[lang] },
      { id: 'solution-overview', title: t.solutionTitle, body: [page.definition[lang]], bullets: page.capabilities[lang] },
      { id: 'key-capabilities', title: t.capabilities, body: [], bullets: page.capabilities[lang] },
      { id: 'workflow', title: t.workflow, body: [], bullets: page.howItWorks[lang] },
      { id: 'governance-impact', title: t.governance, body: [], bullets: page.governance[lang] },
      { id: 'proof', title: t.proof, body: [page.summary[lang]], bullets: page.proof[lang] },
      { id: 'executive-outcomes', title: t.outcomes, body: [], bullets: page.outcomes[lang] },
    ],
  }
}

const pages: Def[] = [
  {
    key: 'aiGovernanceDecisionSupport',
    eyebrow: 'platform',
    titles: { ar: 'الذكاء الاصطناعي في حوكمة القرار', en: 'AI Governance & Decision Support',    hi: 'गवर्नेंस और निर्णय सहायता में AI', ur: 'گورننس اور فیصلے کی معاونت میں AI'},
    summary: { ar: 'يوظف ديوان سويت الذكاء الاصطناعي لتسريع التلخيص، واستخراج القرارات والتوصيات، وتحويل المخرجات إلى عناصر متابعة منظمة دون إلغاء دور المراجعة البشرية.', en: 'Diwan Suite uses AI to accelerate summarization, extract decisions and recommendations, and turn outputs into structured follow-up items without replacing human review.',    hi: 'Diwan Suite AI का उपयोग summarization तेज़ करने, decisions और recommendations निकालने और outputs को structured follow-up items में बदलने के लिए करता है।', ur: 'Diwan Suite AI کا استعمال summarization تیز کرنے، decisions اور recommendations نکالنے اور outputs کو structured follow-up items میں بدلنے کے لیے کرتا ہے۔'},
    seoTitle: { ar: 'الذكاء الاصطناعي في حوكمة القرار | ديوان سويت', en: 'AI Governance & Decision Support | Diwan Suite',    hi: 'गवर्नेंस और निर्णय सहायता में AI | Diwan Suite', ur: 'گورننس اور فیصلے کی معاونت میں AI | Diwan Suite'},
    seoDescription: { ar: 'الذكاء الاصطناعي في ديوان سويت لتلخيص الاجتماعات واستخراج القرارات والتوصيات وتحويلها إلى متابعة منظمة داخل مسار حوكمي منضبط.', en: 'AI in Diwan Suite for meeting summarization, decision extraction, and structured follow-up inside disciplined governance workflows.',    hi: 'Diwan Suite में AI meeting summarization, decision extraction और structured follow-up के लिए disciplined governance workflows के भीतर काम करता है।', ur: 'Diwan Suite میں AI meeting summarization، decision extraction اور structured follow-up کے لیے disciplined governance workflows کے اندر کام کرتا ہے۔'},
    definition: { ar: 'الذكاء الاصطناعي هنا طبقة مساعدة داخل دورة الاجتماع والقرار؛ يسرّع الفهم ويترك الاعتماد النهائي بيد الإنسان.', en: 'AI here is an assistive layer inside the meeting and decision cycle; it accelerates understanding while final approval remains human-led.',    hi: 'यहाँ AI meeting और decision cycle के भीतर एक assistive layer है; final approval मानव के पास रहता है।', ur: 'یہاں AI meeting اور decision cycle کے اندر ایک assistive layer ہے؛ final approval انسان کے پاس رہتا ہے۔'},
    whoFor: { ar: ['أمانات المجالس واللجان', 'القيادات التنفيذية التي تحتاج رؤية أسرع'], en: ['Board and committee secretariats', 'Executive leaders needing faster visibility'],    hi: ['बोर्ड और समिति सचिवालय', 'वे executive leaders जिन्हें तेज़ visibility चाहिए'], ur: ['بورڈ اور کمیٹی سیکرٹریٹس', 'وہ executive leaders جنہیں تیز visibility چاہیے']},
    whatItSolves: { ar: ['تقليل الوقت الضائع في التلخيص اليدوي', 'تنظيم القرارات والتوصيات داخل مسار قابل للمتابعة', 'إظهار مؤشرات التأخير ومخاطر التنفيذ مبكرًا'], en: ['Reduce manual summarization time', 'Organize decisions and recommendations into a follow-up path', 'Surface delay and execution-risk indicators early'],    hi: ['manual summarization समय कम करता है', 'decisions और recommendations को follow-up path में व्यवस्थित करता है', 'delay और execution risk indicators जल्दी दिखाता है'], ur: ['manual summarization کا وقت کم کرتا ہے', 'decisions اور recommendations کو follow-up path میں منظم کرتا ہے', 'delay اور execution risk indicators جلد ظاہر کرتا ہے']},
    howItWorks: { ar: ['قراءة مخرجات الاجتماع واستخراج القرارات والتوصيات', 'تحويلها إلى عناصر متابعة مرتبطة بالمحضر والقرار'], en: ['Read meeting outputs and extract decisions and recommendations', 'Convert them into follow-up items linked to minutes and decisions'],    hi: ['meeting outputs पढ़कर decisions और recommendations निकालता है', 'उन्हें minutes और decisions से जुड़े follow-up items में बदलता है'], ur: ['meeting outputs پڑھ کر decisions اور recommendations نکالتا ہے', 'انہیں minutes اور decisions سے منسلک follow-up items میں بدلتا ہے']},
    capabilities: { ar: ['تلخيص الاجتماعات', 'استخراج القرارات والتوصيات', 'تحليل أولي لمخاطر التنفيذ'], en: ['Meeting summarization', 'Decision and recommendation extraction', 'Initial execution-risk analysis'],    hi: ['meeting summarization', 'decision और recommendation extraction', 'initial execution-risk analysis'], ur: ['meeting summarization', 'decision اور recommendation extraction', 'initial execution-risk analysis']},
    governance: { ar: ['يرفع وضوح القرار قبل وبعد الاعتماد', 'يدعم المساءلة عبر ربط المخرجات بسياقها التنفيذي'], en: ['Improves decision clarity before and after approval', 'Supports accountability by linking outputs to execution context'],    hi: ['approval से पहले और बाद decision clarity बेहतर करता है', 'outputs को execution context से जोड़कर accountability मजबूत करता है'], ur: ['approval سے پہلے اور بعد decision clarity بہتر کرتا ہے', 'outputs کو execution context سے جوڑ کر accountability مضبوط کرتا ہے']},
    proof: { ar: ['مخرجات منظمة قابلة للمراجعة قبل الاعتماد', 'ربط مباشر بين المحضر والقرار والمهام'], en: ['Structured outputs reviewable before approval', 'Direct linkage between minutes, decisions, and tasks'],    hi: ['approval से पहले review योग्य structured outputs', 'minutes, decisions और tasks के बीच direct linkage'], ur: ['approval سے پہلے review کے قابل structured outputs', 'minutes، decisions اور tasks کے درمیان direct linkage']},
    outcomes: { ar: ['اختصار زمن إعداد المحاضر والملخصات', 'رفع قدرة القيادة على المتابعة المبكرة'], en: ['Shorter time to produce minutes and summaries', 'Earlier leadership visibility into follow-up'],    hi: ['minutes और summaries बनाने का समय कम होता है', 'leadership को follow-up पर पहले visibility मिलती है'], ur: ['minutes اور summaries تیار کرنے کا وقت کم ہوتا ہے', 'leadership کو follow-up پر پہلے visibility ملتی ہے']},
    faq: faqMap(
      [['ماذا يفعل الذكاء الاصطناعي داخل النظام؟','يساعد على تلخيص الاجتماعات واستخراج القرارات والتوصيات وتنظيم المخرجات داخل مسار متابعة واضح.'],['هل يستخرج القرارات والتوصيات؟','نعم، يدعم تحويل المخرجات إلى عناصر منظمة قابلة للمراجعة والمتابعة.'],['هل يحلل مخاطر التنفيذ؟','يساعد في إظهار مؤشرات التأخير أو التعثر المبكر لتسهيل التدخل الإداري.'],['هل يساعد قبل اعتماد القرار؟','يمكن استخدامه كطبقة مساعدة قبل الاعتماد النهائي، مع بقاء القرار النهائي بيد الإنسان.']],
      [['What does AI do inside the platform?','It helps summarize meetings, extract decisions and recommendations, and organize outputs into a clear follow-up path.'],['Does it extract decisions and recommendations?','Yes. It supports turning outputs into structured items for review and follow-up.'],['Does it analyze execution risk?','It helps surface early indicators of delay or execution friction so management can intervene earlier.'],['Can it help before final approval?','Yes. It can be used as an assistive layer before final approval while keeping the final decision in human hands.']],
      [['सिस्टम के भीतर AI क्या करता है?','यह meetings summarize करता है, decisions और recommendations निकालता है और outputs को clear follow-up path में व्यवस्थित करता है।'],['क्या यह decisions और recommendations निकालता है?','हाँ। यह outputs को structured review और follow-up items में बदलने में मदद करता है।'],['क्या यह execution risk का analysis करता है?','यह delay या execution friction के शुरुआती संकेत सामने लाने में मदद करता है।'],['क्या यह final approval से पहले मदद कर सकता है?','हाँ। यह final approval से पहले assistive layer की तरह काम कर सकता है, जबकि अंतिम निर्णय मानव के पास रहता है।']],
      [['سسٹم کے اندر AI کیا کرتا ہے؟','یہ meetings کو summarize کرتا ہے، decisions اور recommendations نکالتا ہے اور outputs کو clear follow-up path میں منظم کرتا ہے۔'],['کیا یہ decisions اور recommendations نکالتا ہے؟','جی ہاں، یہ outputs کو structured review اور follow-up items میں بدلنے میں مدد دیتا ہے۔'],['کیا یہ execution risk کا تجزیہ کرتا ہے؟','یہ delay یا execution friction کے ابتدائی اشارے سامنے لانے میں مدد دیتا ہے۔'],['کیا یہ final approval سے پہلے مدد کر سکتا ہے؟','جی ہاں، یہ final approval سے پہلے assistive layer کے طور پر کام کر سکتا ہے، جبکہ آخری فیصلہ انسان کے پاس رہتا ہے۔']]
    ),
    relatedPages: ['boardManagementSystem', 'decisionTracking', 'governanceReportsDashboards'],
  },
  {
    key: 'attendanceQuorumQr',
    eyebrow: 'platform',
    titles: { ar: 'الحضور والنصاب عبر QR', en: 'Attendance, Quorum & QR',    hi: 'उपस्थिति, कोरम और QR', ur: 'حاضری، نصاب اور QR'},
    summary: { ar: 'تنظم الصفحة تسجيل الحضور والاعتذارات واحتساب النصاب باستخدام QR وقواعد تحقق تقلل العبث اليدوي وتربط النتائج مباشرة بالمحضر ولوحات المتابعة.', en: 'This page covers attendance recording, apology handling, quorum calculation, and QR-based check-in with validation rules that reduce manual manipulation and feed the minutes and dashboards directly.',    hi: 'यह पृष्ठ attendance recording, apology handling, quorum calculation और QR-based check-in को कवर करता है, साथ में validation rules जो manual manipulation कम करते हैं।', ur: 'یہ صفحہ attendance recording، apology handling، quorum calculation اور QR-based check-in کو کور کرتا ہے، ساتھ میں validation rules جو manual manipulation کم کرتے ہیں۔'},
    seoTitle: { ar: 'الحضور والنصاب عبر QR | ديوان سويت', en: 'Attendance, Quorum & QR | Diwan Suite',    hi: 'उपस्थिति, कोरम और QR | Diwan Suite', ur: 'حاضری، نصاب اور QR | Diwan Suite'},
    seoDescription: { ar: 'إدارة الحضور والنصاب عبر QR داخل ديوان سويت مع احتساب تلقائي للنصاب، إدراج آلي في المحضر، وتقارير حضور وانضباط قابلة للمتابعة.', en: 'Attendance and quorum management with QR in Diwan Suite, including automated quorum calculation, direct insertion into minutes, and follow-up attendance reporting.',    hi: 'Diwan Suite में QR के साथ attendance और quorum management, automated quorum calculation, minutes insertion और attendance reporting सहित।', ur: 'Diwan Suite میں QR کے ساتھ attendance اور quorum management، automated quorum calculation، minutes insertion اور attendance reporting سمیت۔'},
    definition: { ar: 'الحضور والنصاب عبر QR هو مسار يضمن توثيق المشاركة واحتساب النصاب بصورة أسرع وأكثر انضباطًا مع ربط النتائج تلقائيًا بسجل الاجتماع ومحضره.', en: 'Attendance, quorum, and QR form a workflow that documents participation and calculates quorum faster and with more discipline while linking results automatically to the meeting record and minutes.',    hi: 'attendance, quorum और QR एक workflow बनाते हैं जो participation को document करता है और quorum को तेज़ व अधिक अनुशासित तरीके से calculate करता है।', ur: 'attendance، quorum اور QR ایک workflow بناتے ہیں جو participation کو document کرتا ہے اور quorum کو تیز اور زیادہ منظم انداز میں calculate کرتا ہے۔'},
    whoFor: { ar: ['أمانات المجالس واللجان', 'مسؤولو تنظيم الاجتماعات والحضور'], en: ['Board and committee secretariats', 'Meeting coordinators and attendance owners'],    hi: ['बोर्ड और समिति सचिवालय', 'meeting coordination और attendance owners'], ur: ['بورڈ اور کمیٹی سیکرٹریٹس', 'meeting coordination اور attendance owners']},
    whatItSolves: { ar: ['يقلل الاعتماد على الجداول اليدوية المتفرقة', 'يسهل إدراج الحضور والاعتذارات داخل المحضر تلقائيًا', 'يدعم احتساب النصاب بشكل موحد وقابل للمراجعة'], en: ['Reduces dependence on scattered manual attendance lists', 'Makes it easier to insert attendance and apologies into minutes automatically', 'Supports consistent and reviewable quorum calculation'],    hi: ['scattered manual attendance lists पर निर्भरता कम करता है', 'attendance और apologies को minutes में स्वतः डालना आसान बनाता है', 'consistent और reviewable quorum calculation को समर्थन देता है'], ur: ['scattered manual attendance lists پر انحصار کم کرتا ہے', 'attendance اور apologies کو minutes میں خودکار طور پر شامل کرنا آسان بناتا ہے', 'consistent اور reviewable quorum calculation کو سپورٹ کرتا ہے']},
    howItWorks: { ar: ['يسجل الحضور والاعتذارات من خلال مسار منضبط', 'يحسب النصاب تلقائيًا وفق قواعد الجلسة المعتمدة', 'يربط النتيجة بالمحضر ولوحات المتابعة والتقارير'], en: ['It records attendance and apologies through a disciplined workflow', 'It calculates quorum automatically according to approved meeting rules', 'It connects the result to minutes, dashboards, and reports'],    hi: ['यह disciplined workflow के माध्यम से attendance और apologies रिकॉर्ड करता है', 'approved meeting rules के अनुसार quorum स्वतः calculate करता है', 'और परिणाम को minutes, dashboards और reports से जोड़ता है'], ur: ['یہ disciplined workflow کے ذریعے attendance اور apologies ریکارڈ کرتا ہے', 'approved meeting rules کے مطابق quorum خودکار calculate کرتا ہے', 'اور نتیجے کو minutes، dashboards اور reports سے جوڑتا ہے']},
    capabilities: { ar: ['تسجيل الحضور والاعتذار', 'احتساب النصاب تلقائيًا', 'الحضور عبر QR'], en: ['Attendance and apology recording', 'Automated quorum calculation', 'QR-based attendance'],    hi: ['attendance और apology recording', 'automated quorum calculation', 'QR-based attendance'], ur: ['attendance اور apology recording', 'automated quorum calculation', 'QR-based attendance']},
    governance: { ar: ['يرفع موثوقية النصاب والحضور في الاجتماعات الرسمية', 'يدعم الشفافية عند مراجعة من حضر ومن اعتذر وكيف تحقق النصاب'], en: ['Improves the reliability of quorum and attendance in formal meetings', 'Supports transparency when reviewing who attended, who apologized, and how quorum was achieved'],    hi: ['औपचारिक बैठकों में quorum और attendance की reliability बढ़ाता है', 'कौन उपस्थित था, किसने apology दी, और quorum कैसे बना—इस पर transparency बढ़ती है'], ur: ['رسمی اجلاسوں میں quorum اور attendance کی reliability بڑھاتا ہے', 'کون حاضر تھا، کس نے apology دی، اور quorum کیسے حاصل ہوا—اس پر transparency بڑھتی ہے']},
    proof: { ar: ['سجلات حضور قابلة للمراجعة', 'إظهار النصاب لحظة الانعقاد'], en: ['Reviewable attendance records', 'Visible quorum status at meeting time'],    hi: ['reviewable attendance records', 'meeting time पर visible quorum status'], ur: ['reviewable attendance records', 'meeting time پر visible quorum status']},
    outcomes: { ar: ['سرعة أعلى في توثيق الحضور داخل المحضر', 'تقليل الجهد اليدوي في مراجعة النصاب'], en: ['Faster attendance documentation inside the minutes', 'Less manual effort in quorum review'],    hi: ['minutes में attendance documentation तेज़ होता है', 'quorum review में manual effort कम होता है'], ur: ['minutes میں attendance documentation تیز ہوتی ہے', 'quorum review میں manual effort کم ہوتا ہے']},
    faq: faqMap(
      [['هل يحسب النصاب تلقائياً؟','نعم، يدعم النظام احتساب النصاب وفق القواعد المعتمدة للجلسة أو الجهة.'],['هل يدعم QR؟','نعم، يمكن استخدام QR لتسهيل تسجيل الحضور ضمن مسار منضبط.'],['هل يتم إدراج الحضور تلقائياً في المحضر؟','يدعم ربط بيانات الحضور والاعتذارات بالمحضر وتقارير المتابعة.'],['هل توجد تقارير حضور؟','نعم، تتوفر تقارير ولوحات متابعة تساعد على قراءة الانضباط والحضور بوضوح.']],
      [['Does it calculate quorum automatically?','Yes. The system supports automatic quorum calculation according to the approved meeting rules.'],['Does it support QR?','Yes. QR can be used to simplify attendance recording in a controlled workflow.'],['Is attendance inserted into the minutes automatically?','It supports linking attendance and apologies into the minutes and follow-up reporting.'],['Are attendance reports available?','Yes. Reporting and dashboards help make attendance discipline more visible.']],
      [['क्या यह quorum स्वतः calculate करता है?','हाँ, सिस्टम approved meeting rules के अनुसार quorum का automatic calculation करता है।'],['क्या यह QR support करता है?','हाँ, attendance recording को सरल बनाने के लिए QR उपयोग किया जा सकता है।'],['क्या attendance minutes में स्वतः शामिल होती है?','सिस्टम attendance और apology data को minutes और reporting से जोड़ता है।'],['क्या attendance reports उपलब्ध हैं?','हाँ, reports और dashboards attendance discipline को अधिक स्पष्ट बनाते हैं।']],
      [['کیا یہ quorum خودکار calculate کرتا ہے؟','جی ہاں، سسٹم approved meeting rules کے مطابق quorum کا automatic calculation کرتا ہے۔'],['کیا یہ QR سپورٹ کرتا ہے؟','جی ہاں، attendance recording کو آسان بنانے کے لیے QR استعمال کیا جا سکتا ہے۔'],['کیا attendance minutes میں خودکار شامل ہوتی ہے؟','سسٹم attendance اور apology data کو minutes اور reporting سے جوڑتا ہے۔'],['کیا attendance reports دستیاب ہیں؟','جی ہاں، reports اور dashboards attendance discipline کو زیادہ واضح بناتے ہیں۔']]
    ),
    relatedPages: ['generalAssemblyManagement', 'boardManagementSystem', 'governanceReportsDashboards'],
  },
  {
    key: 'governanceReportsDashboards',
    eyebrow: 'platform',
    titles: { ar: 'التقارير ولوحات التحكم', en: 'Governance Reports & Dashboards',    hi: 'गवर्नेंस रिपोर्ट्स और डैशबोर्ड', ur: 'گورننس رپورٹس اور ڈیش بورڈز'},
    summary: { ar: 'تعطي الصفحة رؤية تنفيذية للتقارير ولوحات التحكم التي تساعد القيادة على فهم الحضور والنصاب وتنفيذ القرارات والانضباط التشغيلي بصورة أسرع وأوضح.', en: 'This page presents executive reporting and dashboards that help leadership understand attendance, quorum, decision execution, and operational discipline more clearly and faster.',    hi: 'यह पृष्ठ executive reporting और dashboards दिखाता है जो leadership को attendance, quorum, decision execution और operational discipline बेहतर समझने में मदद देते हैं।', ur: 'یہ صفحہ executive reporting اور dashboards دکھاتا ہے جو leadership کو attendance، quorum، decision execution اور operational discipline بہتر سمجھنے میں مدد دیتے ہیں۔'},
    seoTitle: { ar: 'التقارير ولوحات التحكم | ديوان سويت', en: 'Governance Reports & Dashboards | Diwan Suite',    hi: 'गवर्नेंस रिपोर्ट्स और डैशबोर्ड | Diwan Suite', ur: 'گورننس رپورٹس اور ڈیش بورڈز | Diwan Suite'},
    seoDescription: { ar: 'تقارير ولوحات تنفيذية لقياس الحضور والنصاب وتنفيذ القرارات والمهام، مع دعم رقابي واضح للقيادة العليا وأمانات المجالس.', en: 'Executive dashboards and reports for attendance, quorum, decisions, and task execution, with clear oversight support for leadership and board offices.',    hi: 'attendance, quorum, decisions और task execution के लिए executive dashboards और reports, leadership और board offices के लिए स्पष्ट oversight support के साथ।', ur: 'attendance، quorum، decisions اور task execution کے لیے executive dashboards اور reports، leadership اور board offices کے لیے واضح oversight support کے ساتھ۔'},
    definition: { ar: 'توفر ديوان سويت تقارير ولوحات متابعة تجعل الإدارة ترى ما حدث، وما الذي نُفذ، وما الذي تأخر، وأين تحتاج دورة الحوكمة إلى تدخل أو تحسين.', en: 'Diwan Suite provides reports and dashboards that show management what happened, what was executed, what was delayed, and where the governance cycle needs intervention or improvement.',    hi: 'Diwan Suite ऐसी reports और dashboards देता है जो management को दिखाते हैं कि क्या हुआ, क्या execute हुआ, क्या delay हुआ और governance cycle में कहाँ सुधार चाहिए।', ur: 'Diwan Suite ایسی reports اور dashboards دیتا ہے جو management کو دکھاتے ہیں کہ کیا ہوا، کیا execute ہوا، کیا delay ہوا اور governance cycle میں کہاں بہتری چاہیے۔'},
    whoFor: { ar: ['القيادات العليا وأعضاء المجلس', 'أمانات المجالس واللجان'], en: ['Executive leadership and board members', 'Board and committee secretariats'],    hi: ['कार्यकारी नेतृत्व और बोर्ड सदस्य', 'बोर्ड और समिति सचिवालय'], ur: ['اعلیٰ قیادت اور بورڈ ممبران', 'بورڈ اور کمیٹی سیکرٹریٹس']},
    whatItSolves: { ar: ['يوحد مؤشرات الحضور والنصاب والتنفيذ في مكان واحد', 'يوفر قراءة أسرع لأثر التحول قبل وبعد التطبيق', 'يسهل على الإدارة مقارنة الأداء بين الاجتماعات واللجان'], en: ['Unifies attendance, quorum, and execution indicators in one place', 'Provides a faster view of operational impact before and after transformation', 'Makes it easier to compare performance across meetings and committees'],    hi: ['attendance, quorum और execution indicators को एक जगह लाता है', 'परिवर्तन से पहले और बाद के प्रभाव को तेजी से दिखाता है', 'मीटिंग्स और समितियों के बीच प्रदर्शन तुलना आसान बनाता है'], ur: ['attendance، quorum اور execution indicators کو ایک جگہ لاتا ہے', 'تبدیلی سے پہلے اور بعد کے اثر کو تیزی سے دکھاتا ہے', 'اجلاسوں اور کمیٹیوں کے درمیان کارکردگی کا موازنہ آسان بناتا ہے']},
    howItWorks: { ar: ['تجمع المنصة بيانات الاجتماعات والقرارات والمهام', 'تولد تقارير تشغيلية وتنفيذية وفق المؤشرات المختارة', 'تتيح قراءة الاتجاهات والانضباط والالتزام عبر لوحات مرئية'], en: ['The platform gathers data from meetings, decisions, and tasks', 'It generates operational and executive reports based on chosen indicators', 'It visualizes trends, discipline, and compliance through dashboards'],    hi: ['प्लेटफ़ॉर्म meetings, decisions और tasks का डेटा एकत्र करता है', 'यह चुने गए indicators के अनुसार reports बनाता है', 'यह dashboards के माध्यम से trends, discipline और compliance दिखाता है'], ur: ['پلیٹ فارم meetings، decisions اور tasks کا ڈیٹا جمع کرتا ہے', 'یہ منتخب indicators کے مطابق reports بناتا ہے', 'یہ dashboards کے ذریعے trends، discipline اور compliance دکھاتا ہے']},
    capabilities: { ar: ['تقارير موجزة للإدارة العليا', 'تقارير الحضور والنصاب والانضباط', 'تقارير تنفيذ القرارات والمهام'], en: ['Executive summary reports', 'Attendance, quorum, and meeting-discipline reports', 'Decision and task execution reports'],    hi: ['executive summary reports', 'attendance, quorum और meeting-discipline reports', 'decision और task execution reports'], ur: ['executive summary reports', 'attendance، quorum اور meeting-discipline reports', 'decision اور task execution reports']},
    governance: { ar: ['تساعد القيادة على اتخاذ قرارات مبنية على المؤشرات لا الانطباعات', 'تربط الحوكمة بالمخرجات التنفيذية لا بالمحفوظات فقط'], en: ['Helps leadership act on indicators instead of impressions', 'Connects governance to execution outcomes rather than static records only'],    hi: ['leadership को impression के बजाय indicators के आधार पर निर्णय लेने में मदद करता है', 'governance को execution outcomes से जोड़ता है'], ur: ['leadership کو impression کے بجائے indicators کی بنیاد پر فیصلہ کرنے میں مدد دیتا ہے', 'governance کو execution outcomes سے جوڑتا ہے']},
    proof: { ar: ['ملخص تنفيذي لكل فترة متابعة', 'تقارير جاهزة للاجتماعات الإدارية والرقابية'], en: ['Executive summaries for each review period', 'Reports ready for management and oversight meetings'],    hi: ['प्रत्येक समीक्षा अवधि के लिए executive summaries', 'management और oversight meetings के लिए तैयार reports'], ur: ['ہر جائزہ مدت کے لیے executive summaries', 'management اور oversight meetings کے لیے تیار reports']},
    outcomes: { ar: ['رؤية أعلى للقيادة على مستوى الحوكمة والتنفيذ', 'وقت أقل لإعداد تقارير رقابية يدوية'], en: ['Higher leadership visibility into governance and execution', 'Less time spent preparing manual oversight reports'],    hi: ['governance और execution पर leadership visibility बढ़ती है', 'manual oversight reports तैयार करने में कम समय लगता है'], ur: ['governance اور execution پر leadership visibility بڑھتی ہے', 'manual oversight reports تیار کرنے میں کم وقت لگتا ہے']},
    faq: faqMap(
      [['ما أنواع التقارير المتاحة؟','تتوفر تقارير حضور ونصاب، تقارير تنفيذ القرارات والمهام، وتقارير موجزة للإدارة العليا.'],['هل توجد مؤشرات أداء للحوكمة؟','نعم، يمكن عرض مؤشرات مرتبطة بالانضباط والتنفيذ والالتزام ضمن لوحات متابعة.'],['هل يمكن تصدير البيانات؟','يمكن إتاحة التصدير وفق الإعدادات والصلاحيات المعتمدة داخل الجهة.'],['هل التقارير جاهزة للإدارة العليا؟','تم تصميمها لتكون مختصرة وواضحة وتدعم القراءة التنفيذية السريعة.']],
      [['What types of reports are available?','Attendance, quorum, decision execution, task follow-up, and executive summary reporting are available.'],['Are governance KPIs available?','Yes. Dashboards can show governance, execution, and discipline indicators.'],['Can data be exported?','Export can be enabled according to approved permissions and settings.'],['Are the reports ready for executive leadership?','Yes. They are designed for concise executive reading and leadership oversight.']],
      [['किस प्रकार की reports उपलब्ध हैं?','attendance, quorum, decision execution, task follow-up और executive summary reports उपलब्ध हैं।'],['क्या governance KPI उपलब्ध हैं?','हाँ। dashboards governance, execution और discipline indicators दिखा सकते हैं।'],['क्या data export किया जा सकता है?','हाँ, approved permissions और settings के अनुसार export सक्षम किया जा सकता है।'],['क्या reports leadership के लिए उपयुक्त हैं?','हाँ। इन्हें concise executive reading और oversight के लिए तैयार किया गया है।']],
      [['کون سی reports دستیاب ہیں؟','attendance، quorum، decision execution، task follow-up اور executive summary reports دستیاب ہیں۔'],['کیا governance KPI موجود ہیں؟','جی ہاں، dashboards governance، execution اور discipline indicators دکھا سکتے ہیں۔'],['کیا data export کیا جا سکتا ہے؟','جی ہاں، approved permissions اور settings کے مطابق export فعال کیا جا سکتا ہے۔'],['کیا reports leadership کے لیے مناسب ہیں؟','جی ہاں، انہیں concise executive reading اور oversight کے لیے تیار کیا گیا ہے۔']]
    ),
    relatedPages: ['decisionTracking', 'boardManagementSystem', 'roiBoardGovernance'],
  },
  {
    key: 'integrationsBoardGovernance',
    eyebrow: 'platform',
    titles: { ar: 'تكاملات النظام', en: 'Board Governance Integrations',    hi: 'बोर्ड गवर्नेंस इंटीग्रेशन', ur: 'بورڈ گورننس انٹیگریشنز'},
    summary: { ar: 'توضح الصفحة كيف يتكامل ديوان سويت مع أدوات الاجتماعات، والتقويم، والأنظمة المؤسسية، وواجهات REST API لضمان استمرارية البيانات التشغيلية.', en: 'This page explains how Diwan Suite integrates with meeting tools, calendars, enterprise systems, and REST APIs to preserve operational data continuity.',    hi: 'यह पृष्ठ बताता है कि Diwan Suite meeting tools, calendars, enterprise systems और REST APIs से कैसे integrate होता है ताकि operational data continuity बनी रहे।', ur: 'یہ صفحہ بتاتا ہے کہ Diwan Suite meeting tools، calendars، enterprise systems اور REST APIs سے کیسے integrate ہوتا ہے تاکہ operational data continuity برقرار رہے۔'},
    seoTitle: { ar: 'تكاملات النظام | ديوان سويت', en: 'Board Governance Integrations | Diwan Suite',    hi: 'बोर्ड गवर्नेंस इंटीग्रेशन | Diwan Suite', ur: 'بورڈ گورننس انٹیگریشنز | Diwan Suite'},
    seoDescription: { ar: 'تكاملات ديوان سويت مع Teams وZoom وWebex وGoogle Calendar وOutlook وDocSuite ECM وواجهات REST API وربط ERP/HCM/CRM.', en: 'Diwan Suite integrations with Teams, Zoom, Webex, Google Calendar, Outlook, DocSuite ECM, REST APIs, and ERP/HCM/CRM systems.',    hi: 'Diwan Suite, Teams, Zoom, Webex, Google Calendar, Outlook, DocSuite ECM, REST APIs और ERP/HCM/CRM सिस्टम्स के साथ इंटीग्रेशन प्रदान करता है।', ur: 'Diwan Suite، Teams، Zoom، Webex، Google Calendar، Outlook، DocSuite ECM، REST APIs اور ERP/HCM/CRM systems کے ساتھ انٹیگریشن فراہم کرتا ہے۔'},
    definition: { ar: 'تكاملات النظام تعني أن إدارة الاجتماع والقرار لا تبقى معزولة، بل ترتبط بالأدوات والسجلات والأنظمة التي تعمل الجهة عليها يوميًا.', en: 'Integrations mean meeting and decision management does not remain isolated, but connects to the tools, systems, and records the organization already uses every day.',    hi: 'Integrations का अर्थ है कि meeting और decision management अलग-थलग न रहकर संगठन के दैनिक tools, systems और records से जुड़ता है।', ur: 'Integrations کا مطلب یہ ہے کہ meeting اور decision management الگ تھلگ نہ رہے بلکہ ادارے کے روزمرہ tools، systems اور records سے جڑ جائے۔'},
    whoFor: { ar: ['فرق تقنية المعلومات والتكامل', 'الجهات التي تبحث عن استمرارية تشغيلية للبيانات'], en: ['IT and integration teams', 'Organizations that need operational data continuity'],    hi: ['IT और integration टीमें', 'वे संस्थाएँ जिन्हें operational data continuity चाहिए'], ur: ['IT اور integration teams', 'وہ ادارے جنہیں operational data continuity چاہیے']},
    whatItSolves: { ar: ['يقلل التكرار اليدوي بين أكثر من نظام', 'يحسن استمرارية البيانات بين الاجتماعات والتقويم والأنظمة المؤسسية'], en: ['Reduces manual duplication across multiple systems', 'Improves continuity between meetings, calendars, and enterprise systems'],    hi: ['multiple systems के बीच manual duplication कम करता है', 'meetings, calendars और enterprise systems के बीच continuity बेहतर करता है'], ur: ['multiple systems کے درمیان manual duplication کم کرتا ہے', 'meetings، calendars اور enterprise systems کے درمیان continuity بہتر کرتا ہے']},
    howItWorks: { ar: ['يتصل بمنصات الاجتماعات مثل Teams وZoom وWebex', 'يتكامل مع التقويم مثل Google Calendar وOutlook', 'يربط المنصة مع DocSuite ECM وواجهات REST API وأنظمة ERP/HCM/CRM عند الحاجة'], en: ['It connects with meeting platforms such as Teams, Zoom, and Webex', 'It integrates with calendars like Google Calendar and Outlook', 'It links the platform with DocSuite ECM, REST APIs, and ERP/HCM/CRM systems when needed'],    hi: ['यह Teams, Zoom और Webex जैसे meeting platforms से जुड़ता है', 'यह Google Calendar और Outlook जैसे calendars से integrate होता है', 'और जरूरत होने पर DocSuite ECM, REST APIs और ERP/HCM/CRM systems से platform को जोड़ता है'], ur: ['یہ Teams، Zoom اور Webex جیسے meeting platforms سے جڑتا ہے', 'یہ Google Calendar اور Outlook جیسے calendars سے integrate ہوتا ہے', 'اور ضرورت ہونے پر DocSuite ECM، REST APIs اور ERP/HCM/CRM systems سے platform کو جوڑتا ہے']},
    capabilities: { ar: ['تكامل مع Teams وZoom وWebex', 'تكامل مع Google Calendar وOutlook', 'REST APIs وربط مؤسسي مع ERP/HCM/CRM'], en: ['Integration with Teams, Zoom, and Webex', 'Integration with Google Calendar and Outlook', 'REST APIs and enterprise linkage with ERP/HCM/CRM'],    hi: ['Teams, Zoom और Webex integration', 'Google Calendar और Outlook integration', 'REST APIs और ERP/HCM/CRM enterprise linkage'], ur: ['Teams، Zoom اور Webex integration', 'Google Calendar اور Outlook integration', 'REST APIs اور ERP/HCM/CRM enterprise linkage']},
    governance: { ar: ['يعزز استمرارية البيانات بدل انقطاعها بين الأنظمة', 'يقلل مخاطر التكرار اليدوي وفقدان السياق'], en: ['Improves data continuity across connected systems', 'Reduces manual duplication and context-loss risks'],    hi: ['connected systems के बीच data continuity बेहतर करता है', 'manual duplication और context-loss risk कम करता है'], ur: ['connected systems کے درمیان data continuity بہتر کرتا ہے', 'manual duplication اور context-loss risk کم کرتا ہے']},
    proof: { ar: ['مسار عمل متصل بدل نقل يدوي متكرر', 'استمرارية أفضل بين الدعوة والاجتماع والوثيقة والتنفيذ'], en: ['Connected workflow instead of repeated manual transfer', 'Better continuity between invitation, meeting, document, and execution'],    hi: ['repeated manual transfer के बजाय connected workflow', 'invitation, meeting, document और execution के बीच बेहतर continuity'], ur: ['repeated manual transfer کے بجائے connected workflow', 'invitation، meeting، document اور execution کے درمیان بہتر continuity']},
    outcomes: { ar: ['استمرارية تشغيلية أفضل للبيانات', 'خفض الأعمال اليدوية بين الأنظمة'], en: ['Better operational data continuity', 'Less manual work across systems'],    hi: ['बेहतर operational data continuity', 'systems के बीच कम manual work'], ur: ['بہتر operational data continuity', 'systems کے درمیان کم manual work']},
    faq: faqMap(
      [['هل يتكامل مع Teams وZoom وWebex؟','نعم، تدعم المنصة التكامل مع أدوات الاجتماعات المستخدمة في البيئات المؤسسية وفق إعدادات الجهة.'],['هل يتكامل مع Google Calendar وOutlook؟','نعم، يدعم الربط مع أدوات التقويم لتسهيل تنظيم الجلسات والمتابعة.'],['هل توجد APIs؟','نعم، يمكن الاعتماد على REST APIs ضمن سيناريوهات التكامل المناسبة.'],['هل يمكن ربطه مع ERP / HCM / CRM؟','نعم، تدعم البنية ربط النظام مع منصات مؤسسية أخرى عند الحاجة.']],
      [['Does it integrate with Teams, Zoom, and Webex?','Yes. The platform supports integrations with enterprise meeting tools according to the organization setup.'],['Does it integrate with Google Calendar and Outlook?','Yes. Calendar integration supports session planning and follow-up continuity.'],['Are APIs available?','Yes. REST APIs can be used in suitable integration scenarios.'],['Can it connect with ERP / HCM / CRM?','Yes. The architecture supports linkage with other enterprise systems when needed.']],
      [['क्या यह Teams, Zoom और Webex से integrate होता है?','हाँ। प्लेटफ़ॉर्म enterprise meeting tools के साथ integration को support करता है।'],['क्या यह Google Calendar और Outlook से integrate होता है?','हाँ। calendar integration planning और continuity में मदद करता है।'],['क्या APIs उपलब्ध हैं?','हाँ। उपयुक्त integration scenarios में REST APIs उपयोग की जा सकती हैं।'],['क्या इसे ERP / HCM / CRM से जोड़ा जा सकता है?','हाँ। architecture अन्य enterprise systems से connection को support करती है।']],
      [['کیا یہ Teams، Zoom اور Webex سے integrate ہوتا ہے؟','جی ہاں، پلیٹ فارم enterprise meeting tools کے ساتھ integration کو support کرتا ہے۔'],['کیا یہ Google Calendar اور Outlook سے integrate ہوتا ہے؟','جی ہاں، calendar integration planning اور continuity میں مدد دیتا ہے۔'],['کیا APIs دستیاب ہیں؟','جی ہاں، مناسب integration scenarios میں REST APIs استعمال کی جا سکتی ہیں۔'],['کیا اسے ERP / HCM / CRM سے جوڑا جا سکتا ہے؟','جی ہاں، architecture دیگر enterprise systems سے connection کو support کرتی ہے۔']]
    ),
    relatedPages: ['boardManagementSystem', 'implementationSupportTraining', 'governanceReportsDashboards'],
  },
  {
    key: 'governanceSecurityCompliance',
    eyebrow: 'trust',
    titles: { ar: 'أمن وامتثال حوكمة الاجتماعات', en: 'Security & Compliance for Meeting Governance',    hi: 'मीटिंग गवर्नेंस के लिए सुरक्षा और अनुपालन', ur: 'میٹنگ گورننس کے لیے سیکیورٹی اور تعمیل'},
    summary: { ar: 'تركز الصفحة على التحكم في الصلاحيات، والتشفير، وسجل التدقيق، والنسخ الاحتياطي والتعافي، وجاهزية المنصة لبيئات تتطلب حوكمة أكثر حساسية وانضباطًا.', en: 'This page focuses on permissions, encryption, audit trail, backup and recovery, and readiness for environments that require stricter governance discipline.',    hi: 'यह पृष्ठ permissions, encryption, audit trail, backup/recovery और उन वातावरणों की readiness पर केंद्रित है जिन्हें अधिक अनुशासित governance चाहिए।', ur: 'یہ صفحہ permissions، encryption، audit trail، backup/recovery اور اُن ماحول کی readiness پر مرکوز ہے جنہیں زیادہ منظم governance درکار ہوتی ہے۔'},
    seoTitle: { ar: 'أمن وامتثال حوكمة الاجتماعات | ديوان سويت', en: 'Security & Compliance for Meeting Governance | Diwan Suite',    hi: 'मीटिंग गवर्नेंस के लिए सुरक्षा और अनुपालन | Diwan Suite', ur: 'میٹنگ گورننس کے لیے سیکیورٹی اور تعمیل | Diwan Suite'},
    seoDescription: { ar: 'أمن وامتثال حوكمة الاجتماعات في ديوان سويت مع صلاحيات دقيقة، تشفير، سجل تدقيق، نسخ احتياطي وتعافي، ودعم بيئات حساسة ومنظمة.', en: 'Security and compliance for meeting governance in Diwan Suite with granular permissions, encryption, audit trail, backup and recovery, and support for sensitive regulated environments.',    hi: 'Diwan Suite में meeting governance के लिए granular permissions, encryption, audit trail, backup/recovery और sensitive regulated environments का समर्थन।', ur: 'Diwan Suite میں meeting governance کے لیے granular permissions، encryption، audit trail، backup/recovery اور sensitive regulated environments کی support۔'},
    definition: { ar: 'أمن وامتثال حوكمة الاجتماعات يعني أن كل اجتماع ووثيقة واعتماد يمر داخل ضوابط واضحة تحفظ السرية وتدعم المراجعة والامتثال المؤسسي.', en: 'Security and compliance in meeting governance means every meeting, document, and approval passes through clear controls that preserve confidentiality and support audit and institutional compliance.',    hi: 'meeting governance में security और compliance का मतलब है कि हर meeting, document और approval स्पष्ट नियंत्रणों से गुजरता है।', ur: 'meeting governance میں security اور compliance کا مطلب ہے کہ ہر meeting، document اور approval واضح controls سے گزرتا ہے۔'},
    whoFor: { ar: ['الجهات الحساسة والمنظمة', 'القطاعات التي تحتاج رقابة داخلية أعلى'], en: ['Sensitive and regulated organizations', 'Sectors requiring stronger internal oversight'],    hi: ['sensitive और regulated organizations', 'वे sectors जिन्हें stronger internal oversight चाहिए'], ur: ['sensitive اور regulated organizations', 'وہ sectors جنہیں stronger internal oversight چاہیے']},
    whatItSolves: { ar: ['يقلل مخاطر الوصول غير المنضبط إلى الوثائق والموافقات', 'يدعم تتبع النشاط والمراجعة عند الحاجة'], en: ['Reduces uncontrolled access risk to records and approvals', 'Supports activity traceability and review when needed'],    hi: ['records और approvals तक uncontrolled access risk कम करता है', 'activity traceability और review को support करता है'], ur: ['records اور approvals تک uncontrolled access risk کم کرتا ہے', 'activity traceability اور review کو support کرتا ہے']},
    howItWorks: { ar: ['يضبط الصلاحيات على مستويات متعددة', 'يحافظ على تشفير مناسب أثناء النقل والتخزين', 'يوثق النشاط والاعتمادات مع النسخ الاحتياطي والتعافي'], en: ['It enforces permissions across multiple levels', 'It maintains suitable encryption in transit and at rest', 'It documents activity and approvals with backup and recovery support'],    hi: ['यह कई स्तरों पर permissions लागू करता है', 'यह transit और at rest दोनों में उपयुक्त encryption बनाए रखता है', 'यह activity और approvals को backup/recovery support के साथ document करता है'], ur: ['یہ کئی سطحوں پر permissions نافذ کرتا ہے', 'یہ transit اور at rest دونوں میں مناسب encryption برقرار رکھتا ہے', 'یہ activity اور approvals کو backup/recovery support کے ساتھ document کرتا ہے']},
    capabilities: { ar: ['صلاحيات دقيقة', 'تشفير', 'سجل تدقيق'], en: ['Granular permissions', 'Encryption', 'Audit trail'],    hi: ['granular permissions', 'encryption', 'audit trail'], ur: ['granular permissions', 'encryption', 'audit trail']},
    governance: { ar: ['تعزيز الامتثال المؤسسي والجاهزية الرقابية', 'تقليل مخاطر فقدان السياق أو تعديل السجلات دون تتبع'], en: ['Strengthens institutional compliance and oversight readiness', 'Reduces the risk of untracked changes or context loss'],    hi: ['institutional compliance और oversight readiness को मजबूत करता है', 'untracked changes और context loss के जोखिम को घटाता है'], ur: ['institutional compliance اور oversight readiness کو مضبوط کرتا ہے', 'untracked changes اور context loss کے خطرے کو کم کرتا ہے']},
    proof: { ar: ['ضوابط وصول قابلة للمراجعة', 'أنشطة واعتمادات مؤرشفة زمنيًا'], en: ['Reviewable access controls', 'Time-stamped activities and approvals'],    hi: ['reviewable access controls', 'time-stamped activities and approvals'], ur: ['reviewable access controls', 'time-stamped activities and approvals']},
    outcomes: { ar: ['بيئة أكثر انضباطًا للوثائق والاعتمادات', 'رؤية أوضح للمخاطر والالتزام'], en: ['A more disciplined environment for documents and approvals', 'Clearer visibility into risk and compliance'],    hi: ['documents और approvals के लिए अधिक disciplined environment', 'risk और compliance पर clearer visibility'], ur: ['documents اور approvals کے لیے زیادہ disciplined environment', 'risk اور compliance پر clearer visibility']},
    faq: faqMap(
      [['كيف يحمي بيانات المجالس؟','من خلال ضوابط وصول مناسبة، وتوثيق النشاط، ودعم حماية البيانات أثناء التخزين والنقل.'],['هل يدعم التشفير؟','نعم، تدعم البنية حماية البيانات أثناء النقل وفي بيئة التشغيل المناسبة.'],['هل توجد نسخ احتياطية وتعافي؟','تدعم المنصة النسخ الاحتياطي والتعافي ضمن بيئة تشغيل منضبطة.'],['هل يوجد سجل تدقيق؟','نعم، يوجد سجل يساعد على مراجعة الوصول والاعتمادات والنشاط المرتبط بالاجتماعات.']],
      [['How does it protect board data?','Through suitable access controls, activity records, and support for protected data handling in transit and storage.'],['Does it support encryption?','Yes. The architecture supports protected handling of data in transit and in suitable operating environments.'],['Are backup and recovery available?','The platform supports backup and recovery within disciplined operating environments.'],['Is there an audit trail?','Yes. An audit trail supports review of access, approvals, and meeting-related activity.']],
      [['यह बोर्ड डेटा की सुरक्षा कैसे करता है?','उपयुक्त access controls, activity records और transit/storage में protected handling के माध्यम से।'],['क्या यह encryption support करता है?','हाँ। architecture transit और उपयुक्त operating environments में protected data handling को support करती है।'],['क्या backup और recovery उपलब्ध हैं?','platform disciplined operating environments में backup और recovery को support करती है।'],['क्या audit trail है?','हाँ। audit trail access, approvals और meeting activity की review में मदद करता है।']],
      [['یہ بورڈ ڈیٹا کی حفاظت کیسے کرتا ہے؟','مناسب access controls، activity records اور transit/storage میں protected handling کے ذریعے۔'],['کیا یہ encryption support کرتا ہے؟','جی ہاں، architecture transit اور مناسب operating environments میں protected data handling کو support کرتی ہے۔'],['کیا backup اور recovery دستیاب ہیں؟','platform disciplined operating environments میں backup اور recovery کو support کرتی ہے۔'],['کیا audit trail ہے؟','جی ہاں، audit trail access، approvals اور meeting activity کی review میں مدد دیتا ہے۔']]
    ),
    relatedPages: ['governmentGovernance', 'bankingGovernance', 'integrationsBoardGovernance'],
  },
  {
    key: 'roiBoardGovernance',
    eyebrow: 'platform',
    titles: { ar: 'العائد على الاستثمار في حوكمة الاجتماعات', en: 'ROI & Operational Impact in Board Governance',    hi: 'बोर्ड गवर्नेंस में ROI और परिचालन प्रभाव', ur: 'بورڈ گورننس میں ROI اور آپریشنل اثر'},
    summary: { ar: 'تعرض الصفحة الأثر التشغيلي المتوقع من ضبط دورة الاجتماعات، وتسريع إعداد المحاضر، ورفع تنفيذ القرارات، وتقليل الأعمال اليدوية والمخاطر التشغيلية، بصياغة تقديرية غير مبالغ فيها.', en: 'This page explains the expected operational impact of structuring meeting governance, accelerating minutes preparation, improving decision execution, and reducing manual effort and operational risk using careful scenario-based wording.',    hi: 'यह पृष्ठ meeting governance को संरचित करने और manual effort व operational risk कम करने से होने वाले expected impact को सावधानीपूर्वक समझाता है।', ur: 'یہ صفحہ meeting governance کو منظم کرنے اور manual effort و operational risk کم کرنے سے ہونے والے expected impact کو محتاط انداز میں بیان کرتا ہے۔'},
    seoTitle: { ar: 'العائد على الاستثمار في حوكمة الاجتماعات | ديوان سويت', en: 'ROI & Operational Impact in Board Governance | Diwan Suite',    hi: 'बोर्ड गवर्नेंस में ROI और परिचालन प्रभाव | Diwan Suite', ur: 'بورڈ گورننس میں ROI اور آپریشنل اثر | Diwan Suite'},
    seoDescription: { ar: 'العائد على الاستثمار في حوكمة الاجتماعات عبر تقليل الأعمال اليدوية، وتسريع اعتماد المحاضر، ورفع تنفيذ القرارات، وفق أثر تشغيلي تقديري يعتمد على نضج الجهة.', en: 'ROI in board governance through reduced manual effort, faster minutes approval, and improved decision execution using scenario-based operational impact depending on organizational maturity.',    hi: 'manual effort घटाने, minutes approval तेज़ करने और decision execution सुधारने के माध्यम से board governance ROI, जो organizational maturity पर निर्भर करता है।', ur: 'manual effort کم کرنے، minutes approval تیز کرنے اور decision execution بہتر کرنے کے ذریعے board governance ROI، جو organizational maturity پر منحصر ہے۔'},
    definition: { ar: 'العائد على الاستثمار في حوكمة الاجتماعات لا يُقاس بوعد رقمي ثابت، بل بما يمكن تحقيقه من تقليل الأعمال اليدوية ورفع الانضباط والوضوح التنفيذي حسب نضج التشغيل داخل الجهة.', en: 'ROI in meeting governance is not a fixed promise, but a measurable business case built on reduced manual work, stronger discipline, and clearer executive follow-up depending on operating maturity.',    hi: 'meeting governance में ROI कोई fixed promise नहीं है, बल्कि manual work घटने और discipline बढ़ने पर आधारित measurable business case है।', ur: 'meeting governance میں ROI کوئی fixed promise نہیں بلکہ manual work کم ہونے اور discipline بڑھنے پر مبنی measurable business case ہے۔'},
    whoFor: { ar: ['القيادات العليا الراعية للتحول', 'الجهات التي تبني مبررًا تشغيليًا للاستثمار'], en: ['Executive sponsors of transformation', 'Organizations building an operational business case for investment'],    hi: ['transformation के executive sponsors', 'वे संस्थाएँ जो investment के लिए operational business case बनाती हैं'], ur: ['transformation کے executive sponsors', 'وہ ادارے جو investment کے لیے operational business case بناتے ہیں']},
    whatItSolves: { ar: ['يقلل الأعمال اليدوية في جمع الوثائق وتجهيز المحاضر والمتابعة', 'يساعد في تقليل التأخير الناتج عن غياب الوضوح والتتبع'], en: ['Reduces manual work in collecting documents, preparing minutes, and follow-up', 'Helps reduce delays caused by poor visibility and weak tracking'],    hi: ['documents, minutes preparation और follow-up में manual work कम करता है', 'poor visibility और weak tracking से होने वाली delays को कम करने में मदद करता है'], ur: ['documents، minutes preparation اور follow-up میں manual work کم کرتا ہے', 'poor visibility اور weak tracking سے ہونے والی delays کو کم کرنے میں مدد دیتا ہے']},
    howItWorks: { ar: ['تربط المنصة بين الدعوة والاجتماع والمحضر والقرار والتنفيذ داخل دورة واحدة', 'تقيس الوقت والانضباط وحالة التنفيذ قبل وبعد التحول عند توفر البيانات'], en: ['The platform connects invitation, meeting, minutes, decision, and execution in one operating cycle', 'It measures time, discipline, and execution status before and after transformation when data is available'],    hi: ['प्लेटफ़ॉर्म invitation, meeting, minutes, decision और execution को एक ही operating cycle में जोड़ता है', 'data उपलब्ध होने पर यह transformation से पहले और बाद के time, discipline और execution status को मापता है'], ur: ['پلیٹ فارم invitation، meeting، minutes، decision اور execution کو ایک ہی operating cycle میں جوڑتا ہے', 'data موجود ہونے پر یہ transformation سے پہلے اور بعد کے time، discipline اور execution status کو measure کرتا ہے']},
    capabilities: { ar: ['تقليل زمن إعداد واعتماد المحاضر', 'تقليل الأعمال اليدوية', 'رفع تنفيذ القرارات'], en: ['Shorter time to prepare and approve minutes', 'Reduced manual work', 'Improved decision execution'],    hi: ['minutes prepare और approve करने का कम समय', 'manual work में कमी', 'decision execution में सुधार'], ur: ['minutes prepare اور approve کرنے میں کم وقت', 'manual work میں کمی', 'decision execution میں بہتری']},
    governance: { ar: ['يساعد القيادة على قراءة الأثر بلغة تشغيلية مفهومة', 'يربط الاستثمار بنتائج يمكن تتبعها ومراجعتها'], en: ['Helps leadership read impact in operational language they can use', 'Links investment to outcomes that can be reviewed and tracked'],    hi: ['leadership को operational भाषा में impact पढ़ने में मदद करता है', 'investment को reviewable और trackable outcomes से जोड़ता है'], ur: ['leadership کو operational زبان میں impact سمجھنے میں مدد دیتا ہے', 'investment کو reviewable اور trackable outcomes سے جوڑتا ہے']},
    proof: { ar: ['سيناريوهات أثر متوقعة حسب درجة النضج التشغيلي', 'مقارنة قبل/بعد عندما تكون البيانات متوفرة'], en: ['Expected-impact scenarios based on operational maturity', 'Before/after comparison when data exists'],    hi: ['operational maturity के आधार पर expected-impact scenarios', 'data होने पर before/after comparison'], ur: ['operational maturity کی بنیاد پر expected-impact scenarios', 'data ہونے پر before/after comparison']},
    outcomes: { ar: ['مبرر تشغيلي أوضح للاستثمار', 'فهم أفضل لمواضع الهدر والتأخير'], en: ['A clearer operational business case for investment', 'Better visibility into waste and delay points'],    hi: ['investment के लिए clearer operational business case', 'waste और delay points पर बेहतर visibility'], ur: ['investment کے لیے clearer operational business case', 'waste اور delay points پر بہتر visibility']},
    faq: faqMap(
      [['كيف يقلل الأعمال اليدوية؟','من خلال ربط الدعوة والاجتماع والمحضر والقرار والتنفيذ داخل دورة واحدة تقلل التكرار اليدوي.'],['كيف يسرّع اعتماد المحاضر؟','عندما تصبح المدخلات أوضح ومسارات الاعتماد أكثر تنظيمًا يقل الوقت اللازم للمراجعة والاعتماد.'],['كيف يساعد على رفع تنفيذ القرارات؟','بربط القرار بالمسؤول والمهلة والمتابعة والتنبيه، ما يرفع وضوح التنفيذ والانضباط.'],['كيف يمكن قياس الأثر؟','يُقاس الأثر بمؤشرات قبل/بعد أو بسيناريوهات تشغيلية متوقعة وفق نضج الجهة وبياناتها.']],
      [['How does it reduce manual work?','By connecting invitation, meeting, minutes, decisions, and execution inside one operating cycle, reducing repeated manual transfer.'],['How does it accelerate minutes approval?','Clearer inputs and more disciplined approval paths reduce the time required for review and approval.'],['How does it help improve decision execution?','By linking decisions to owners, deadlines, follow-up, and alerts, it improves execution visibility and discipline.'],['How can impact be measured?','Impact can be measured through before/after indicators or expected operational scenarios depending on maturity and available data.']],
      [['यह manual work कैसे कम करता है?','invitation, meeting, minutes, decision और execution को एक operating cycle में जोड़कर repeated manual transfer कम करता है।'],['यह minutes approval कैसे तेज़ करता है?','clearer inputs और अधिक disciplined approval paths review समय कम करते हैं।'],['यह decision execution कैसे बेहतर करता है?','decision को owner, deadline, follow-up और alerts से जोड़कर execution visibility बढ़ती है।'],['impact कैसे मापा जा सकता है?','before/after indicators या maturity और available data के अनुसार expected operational scenarios से।']],
      [['یہ manual work کیسے کم کرتا ہے؟','invitation، meeting، minutes، decision اور execution کو ایک operating cycle میں جوڑ کر repeated manual transfer کم کرتا ہے۔'],['یہ minutes approval کیسے تیز کرتا ہے؟','clearer inputs اور زیادہ disciplined approval paths review وقت کم کرتے ہیں۔'],['یہ decision execution کیسے بہتر کرتا ہے؟','decision کو owner، deadline، follow-up اور alerts سے جوڑ کر execution visibility بہتر ہوتی ہے۔'],['impact کیسے ناپا جا سکتا ہے؟','before/after indicators یا maturity اور available data کے مطابق expected operational scenarios سے۔']]
    ),
    relatedPages: ['decisionTracking', 'governanceReportsDashboards', 'boardManagementSystem'],
  },
  {
    key: 'implementationSupportTraining',
    eyebrow: 'support',
    titles: { ar: 'التطبيق والدعم والتدريب', en: 'Implementation, Support & Training',    hi: 'कार्यान्वयन, सहायता और प्रशिक्षण', ur: 'نفاذ، سپورٹ اور تربیت'},
    summary: { ar: 'تغطي الصفحة مراحل التطبيق والتدريب والدعم الفني والتحسينات الدورية، بما يضمن استمرارية تشغيلية أكثر نضجًا بعد الإطلاق.', en: 'This page covers onboarding, training, support channels, updates, and improvement cycles to ensure stronger operational continuity after go-live.',    hi: 'यह पृष्ठ onboarding, training, support channels, updates और improvement cycles को कवर करता है ताकि go-live के बाद operational continuity मजबूत हो।', ur: 'یہ صفحہ onboarding، training، support channels، updates اور improvement cycles کو کور کرتا ہے تاکہ go-live کے بعد operational continuity مضبوط ہو۔'},
    seoTitle: { ar: 'التطبيق والدعم والتدريب | ديوان سويت', en: 'Implementation, Support & Training | Diwan Suite',    hi: 'कार्यान्वयन, सहायता और प्रशिक्षण | Diwan Suite', ur: 'نفاذ، سپورٹ اور تربیت | Diwan Suite'},
    seoDescription: { ar: 'التطبيق والدعم والتدريب في ديوان سويت مع onboarding، دعم فني، قنوات مساندة، تحديثات، وتحسينات تشغيلية لضمان الاستمرارية.', en: 'Implementation, support, and training in Diwan Suite with onboarding, technical support, service channels, updates, and operational improvements for continuity.',    hi: 'Diwan Suite में implementation, support और training में onboarding, technical support, service channels, updates और continuity improvements शामिल हैं।', ur: 'Diwan Suite میں implementation، support اور training میں onboarding، technical support، service channels، updates اور continuity improvements شامل ہیں۔'},
    definition: { ar: 'التطبيق والدعم والتدريب يعني أن المنصة لا تتوقف عند التوريد، بل تمتد إلى التهيئة، والتبنّي التشغيلي، والمساندة الفنية، والتحسين المستمر.', en: 'Implementation, support, and training mean the platform does not stop at delivery, but extends into setup, operational adoption, technical assistance, and continuous improvement.',    hi: 'implementation, support और training का अर्थ है कि प्लेटफ़ॉर्म सिर्फ delivery तक सीमित नहीं रहता बल्कि setup, operational adoption, technical assistance और continuous improvement तक जाता है।', ur: 'implementation، support اور training کا مطلب یہ ہے کہ پلیٹ فارم صرف delivery تک محدود نہیں رہتا بلکہ setup، operational adoption، technical assistance اور continuous improvement تک جاتا ہے۔'},
    whoFor: { ar: ['الجهات التي تطبق النظام لأول مرة', 'الفرق التشغيلية والإدارية'], en: ['Organizations implementing the platform for the first time', 'Operational and administrative teams'],    hi: ['वे संस्थाएँ जो पहली बार प्लेटफ़ॉर्म लागू कर रही हैं', 'operational और administrative टीमें'], ur: ['وہ ادارے جو پہلی بار پلیٹ فارم نافذ کر رہے ہیں', 'operational اور administrative teams']},
    whatItSolves: { ar: ['يقلل ارتباك البداية والتبني غير المنظم', 'يحسن استمرارية الاستخدام بعد الإطلاق'], en: ['Reduces early adoption confusion and unstructured rollout', 'Improves continuity after go-live'],    hi: ['शुरुआती adoption confusion और unstructured rollout को कम करता है', 'go-live के बाद continuity बेहतर करता है'], ur: ['ابتدائی adoption confusion اور unstructured rollout کو کم کرتا ہے', 'go-live کے بعد continuity بہتر کرتا ہے']},
    howItWorks: { ar: ['تبدأ المرحلة بالتهيئة والتخطيط والأدوار', 'تتبعها جلسات تدريب وتمكين وتشغيل عملي', 'ثم تستمر عبر الدعم الفني والتحديثات والتحسينات المتدرجة'], en: ['The journey starts with setup, planning, and role alignment', 'It is followed by training, enablement, and practical operation', 'Then it continues through technical support, updates, and incremental improvements'],    hi: ['यह यात्रा setup, planning और role alignment से शुरू होती है', 'फिर training, enablement और practical operation आता है', 'इसके बाद technical support, updates और incremental improvements चलते रहते हैं'], ur: ['یہ سفر setup، planning اور role alignment سے شروع ہوتا ہے', 'اس کے بعد training، enablement اور practical operation آتا ہے', 'پھر technical support، updates اور incremental improvements جاری رہتے ہیں']},
    capabilities: { ar: ['Onboarding منظم', 'دعم فني وقنوات مساندة', 'تدريب وتمكين'], en: ['Structured onboarding', 'Technical support and service channels', 'Training and enablement'],    hi: ['structured onboarding', 'technical support और service channels', 'training और enablement'], ur: ['structured onboarding', 'technical support اور service channels', 'training اور enablement']},
    governance: { ar: ['يدعم تبنيًا أكثر انضباطًا بعد الإطلاق', 'يقلل مخاطر تعطل الاستخدام أو ضعف الاستفادة'], en: ['Supports more disciplined post-launch adoption', 'Reduces the risk of weak usage or operational drift'],    hi: ['launch के बाद अधिक disciplined adoption को support करता है', 'weak usage या operational drift के जोखिम को कम करता है'], ur: ['launch کے بعد زیادہ disciplined adoption کو support کرتا ہے', 'weak usage یا operational drift کے خطرے کو کم کرتا ہے']},
    proof: { ar: ['خطة تطبيق وتمكين', 'قنوات دعم واضحة'], en: ['Implementation and enablement plan', 'Clear support channels'],    hi: ['implementation और enablement plan', 'clear support channels'], ur: ['implementation اور enablement plan', 'clear support channels']},
    outcomes: { ar: ['استمرارية تشغيلية أعلى بعد الإطلاق', 'وضوح أكبر في قنوات المساندة'], en: ['Stronger operational continuity after go-live', 'Clearer support paths'],    hi: ['go-live के बाद stronger operational continuity', 'clearer support paths'], ur: ['go-live کے بعد stronger operational continuity', 'clearer support paths']},
    faq: faqMap(
      [['هل توجد خطة تطبيق وتدريب؟','نعم، يدعم المشروع خطة تطبيق وتمكين وتدريب تتناسب مع طبيعة الجهة وآلية العمل لديها.'],['ما قنوات الدعم؟','يمكن توفير قنوات دعم معتمدة وفق نطاق الخدمة وآلية التشغيل المتفق عليها.'],['هل توجد اتفاقية مستوى خدمة؟','يمكن تنظيم مستويات الخدمة وآليات الاستجابة وفق الترتيب التعاقدي المناسب.'],['هل توجد تحديثات دورية؟','تدعم المنصة التحديثات والتحسينات المستمرة بما يخدم الاستقرار والتطوير.']],
      [['Is there an implementation and training plan?','Yes. The project supports onboarding, enablement, and training aligned with the organization operating model.'],['What support channels are available?','Support channels can be provided according to the agreed service scope and operating model.'],['Is there an SLA?','Service levels and response models can be organized according to the appropriate contractual setup.'],['Are regular updates available?','The platform supports ongoing updates and improvements to serve stability and development.']],
      [['क्या implementation और training plan है?','हाँ। प्रोजेक्ट onboarding, enablement और training को organization operating model के अनुसार support करता है।'],['कौन से support channels उपलब्ध हैं?','agreed service scope और operating model के अनुसार support channels प्रदान किए जा सकते हैं।'],['क्या SLA है?','service levels और response models को contractual setup के अनुसार व्यवस्थित किया जा सकता है।'],['क्या नियमित updates उपलब्ध हैं?','platform स्थिरता और विकास के लिए ongoing updates और improvements को support करती है।']],
      [['کیا implementation اور training plan موجود ہے؟','جی ہاں، پروجیکٹ onboarding، enablement اور training کو organization operating model کے مطابق support کرتا ہے۔'],['کون سے support channels دستیاب ہیں؟','agreed service scope اور operating model کے مطابق support channels فراہم کیے جا سکتے ہیں۔'],['کیا SLA موجود ہے؟','service levels اور response models کو contractual setup کے مطابق منظم کیا جا سکتا ہے۔'],['کیا باقاعدہ updates دستیاب ہیں؟','platform stability اور development کے لیے ongoing updates اور improvements کو support کرتی ہے۔']]
    ),
    relatedPages: ['integrationsBoardGovernance', 'boardManagementSystem', 'support'],
  },
]

export const phase3cPageCopy: Record<LangCode, Record<Phase3CPageKey, InternalPageCopy>> = {
  ar: {} as Record<Phase3CPageKey, InternalPageCopy>,
  en: {} as Record<Phase3CPageKey, InternalPageCopy>,
  hi: {} as Record<Phase3CPageKey, InternalPageCopy>,
  ur: {} as Record<Phase3CPageKey, InternalPageCopy>,
}

for (const lang of Object.keys(labels) as LangCode[]) {
  for (const page of pages) {
    phase3cPageCopy[lang][page.key] = copy(lang, page)
  }
}
